
using UnityEngine;
using System;

public sealed class DesolationRuntime:MonoBehaviour{
enum S{Menu,Saves,Settings,Feedback,Credits,Game}
S s=S.Menu;Camera cam;GameObject root;Texture2D gold,black,panel,shade,dim;GUIStyle title,sub,head,lab,btn,field;float master=.9f,music=.7f,sfx=.8f,bright=.9f,sens=1f;int gfx=2,slot,issue;string feedback="",email="",msg="";string[] issues={"BUG","BALANCE","PERFORMANCE","IDEA","OTHER"};
void Start(){Application.targetFrameRate=60;Screen.sleepTimeout=SleepTimeout.NeverSleep;LoadPrefs();MakeTex();MakeStyles();MakeWorld();}
void LoadPrefs(){master=PlayerPrefs.GetFloat("ui_master",.9f);music=PlayerPrefs.GetFloat("ui_music",.7f);sfx=PlayerPrefs.GetFloat("ui_sfx",.8f);bright=PlayerPrefs.GetFloat("ui_brightness",.9f);sens=PlayerPrefs.GetFloat("ui_sensitivity",1f);gfx=PlayerPrefs.GetInt("graphics",2);AudioListener.volume=master;}
void SavePrefs(){PlayerPrefs.SetFloat("ui_master",master);PlayerPrefs.SetFloat("ui_music",music);PlayerPrefs.SetFloat("ui_sfx",sfx);PlayerPrefs.SetFloat("ui_brightness",bright);PlayerPrefs.SetFloat("ui_sensitivity",sens);PlayerPrefs.SetInt("graphics",gfx);PlayerPrefs.Save();AudioListener.volume=master;Application.targetFrameRate=gfx==0?30:60;}
Texture2D T(Color c){Texture2D t=new Texture2D(1,1);t.SetPixel(0,0,c);t.Apply();return t;}
void MakeTex(){gold=T(new Color(1f,.78f,.16f,.95f));black=T(new Color(0,0,0,.78f));panel=T(new Color(0,0,0,.42f));shade=T(new Color(0,0,0,.32f));dim=T(new Color(.48f,.36f,.06f,.45f));}
void MakeStyles(){title=new GUIStyle(GUI.skin.label){fontSize=72,fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter};title.normal.textColor=new Color(1f,.82f,.3f);sub=new GUIStyle(title){fontSize=30};head=new GUIStyle(title){fontSize=44};lab=new GUIStyle(GUI.skin.label){fontSize=25,fontStyle=FontStyle.Bold,wordWrap=true};lab.normal.textColor=new Color(1f,.82f,.3f);btn=new GUIStyle(GUI.skin.button){fontSize=30,fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter};btn.normal.background=T(new Color(0,0,0,0));btn.hover.background=btn.normal.background;btn.active.background=dim;btn.normal.textColor=new Color(1f,.82f,.3f);btn.hover.textColor=Color.white;field=new GUIStyle(GUI.skin.textField){fontSize=24,wordWrap=true};field.normal.textColor=new Color(1f,.82f,.3f);field.focused.textColor=Color.white;}
Material M(Color c,float e=0){Material m=new Material(Shader.Find("Standard"));m.color=c;if(e>0){m.EnableKeyword("_EMISSION");m.SetColor("_EmissionColor",c*e);}return m;}
void MakeWorld(){root=new GameObject("MenuBackrooms");cam=new GameObject("MenuCamera").AddComponent<Camera>();cam.transform.position=new Vector3(0,1.55f,-10);cam.transform.rotation=Quaternion.Euler(5,0,0);cam.fieldOfView=55;cam.clearFlags=CameraClearFlags.SolidColor;cam.backgroundColor=new Color(.02f,.015f,.006f);cam.gameObject.AddComponent<AudioListener>();Material wall=M(new Color(.55f,.48f,.18f),.06f),floor=M(new Color(.18f,.13f,.06f)),ceil=M(new Color(.25f,.23f,.16f));for(int i=0;i<10;i++){Box(new Vector3(0,-.05f,i*5),new Vector3(18,.1f,5),floor);Box(new Vector3(0,2.65f,i*5),new Vector3(18,.1f,5),ceil);Box(new Vector3(-9,1.25f,i*5),new Vector3(.25f,2.5f,5),wall);Box(new Vector3(9,1.25f,i*5),new Vector3(.25f,2.5f,5),wall);Box(new Vector3(-3+(i%3)*3,1.25f,4+i*5),new Vector3(1.1f,2.5f,1.1f),wall);Light l=new GameObject("light").AddComponent<Light>();l.transform.SetParent(root.transform);l.transform.position=new Vector3(i%2==0?-4:4,2.45f,i*5+2);l.type=LightType.Point;l.range=8;l.intensity=.65f;l.color=new Color(1f,.8f,.3f);Box(l.transform.position,new Vector3(1.4f,.05f,.5f),M(new Color(1f,.8f,.25f),.8f));}}
void Box(Vector3 p,Vector3 sc,Material m){GameObject g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.transform.SetParent(root.transform);g.transform.position=p;g.transform.localScale=sc;g.GetComponent<Renderer>().material=m;Destroy(g.GetComponent<Collider>());}
void Update(){if(cam)cam.transform.position=new Vector3(Mathf.Sin(Time.time*.08f)*.6f,1.55f,-10+Mathf.Cos(Time.time*.05f)*.7f);if(Input.GetKeyDown(KeyCode.Escape)||Input.GetKeyDown(KeyCode.Backspace))Back();}
void OnGUI(){GUI.DrawTexture(new Rect(0,0,Screen.width,Screen.height),shade);if(s==S.Menu)Menu();else if(s==S.Saves)Saves();else if(s==S.Settings)Settings();else if(s==S.Feedback)Feedback();else if(s==S.Credits)Credits();else Game();}
void Brand(string h){Glow(new Rect(0,28,Screen.width,86),"D E S O L A T I O N :",title);Glow(new Rect(0,108,Screen.width,42),"T H E   B A C K R O O M S",sub);Glow(new Rect(0,186,Screen.width,56),h,head);Line(new Rect(Screen.width*.42f,250,Screen.width*.16f,2));}
void Menu(){Glow(new Rect(Screen.width*.27f,35,Screen.width*.62f,92),"D E S O L A T I O N :",title);Glow(new Rect(Screen.width*.34f,125,Screen.width*.45f,42),"T H E   B A C K R O O M S",sub);Choice(new Rect(58,Screen.height*.23f,230,80),"PLAY",()=>s=S.Saves);Choice(new Rect(58,Screen.height*.42f,310,80),"SETTINGS",()=>s=S.Settings);Choice(new Rect(58,Screen.height*.68f,260,80),"CREDITS",()=>s=S.Credits);Choice(new Rect(Screen.width-310,Screen.height-115,260,70),"FEEDBACK",()=>s=S.Feedback);}
void Saves(){Brand("S A V E S");float gap=Screen.width*.04f,w=(Screen.width-gap*4)/3,y=Screen.height*.31f;for(int i=0;i<3;i++){Rect c=new Rect(gap+i*(w+gap),y,w,Screen.height*.42f);Panel(c);GUI.Label(new Rect(c.x,c.y+25,c.width,50),"S A V E  "+(i+1),Center(38));Line(new Rect(c.x+38,c.y+90,c.width-76,2));GUI.Label(new Rect(c.x+40,c.y+112,c.width-80,75),PlayerPrefs.GetInt("slot_"+i+"_saved",0)==1?"Backrooms\nLevel 0":"New\nRun",Center(26));Preview(new Rect(c.x+35,c.y+c.height-150,c.width-70,112),i);if(GUI.Button(c,"",Clear())){slot=i;PlayerPrefs.SetInt("slot_"+i+"_saved",1);PlayerPrefs.Save();s=S.Game;msg="SAVE "+(i+1)+" SELECTED - LEVEL 0";}}Gold(new Rect(Screen.width/2-85,Screen.height-86,170,56),"BACK",()=>s=S.Menu);}
void Settings(){Brand("S E T T I N G S");Rect p=new Rect(Screen.width*.24f,Screen.height*.28f,Screen.width*.52f,Screen.height*.52f);Panel(p);float y=p.y+24;master=Slide(p.x+40,y,p.width-80,"MASTER VOLUME",master,0,1);y+=76;music=Slide(p.x+40,y,p.width-80,"MUSIC VOLUME",music,0,1);y+=76;sfx=Slide(p.x+40,y,p.width-80,"SFX VOLUME",sfx,0,1);y+=76;bright=Slide(p.x+40,y,p.width-80,"BRIGHTNESS",bright,.35f,1.2f);y+=76;sens=Slide(p.x+40,y,p.width-80,"SENSITIVITY",sens,.35f,2);y+=76;GUI.Label(new Rect(p.x+40,y+9,220,40),"GRAPHICS",lab);string[] n={"LOW","MEDIUM","HIGH"};for(int i=0;i<3;i++){Rect r=new Rect(p.x+p.width-335+i*112,y,98,48);if(gfx==i)GUI.DrawTexture(new Rect(r.x-5,r.y-5,r.width+10,r.height+10),dim);if(GUI.Button(r,n[i],btn))gfx=i;Border(r);}Gold(new Rect(Screen.width/2-100,Screen.height-76,200,56),"BACK",()=>{SavePrefs();s=S.Menu;});}
float Slide(float x,float y,float w,string l,float v,float mn,float mx){GUI.Label(new Rect(x,y,270,40),l,lab);Rect tr=new Rect(x+305,y+19,w-330,6);GUI.DrawTexture(tr,dim);float nv=GUI.HorizontalSlider(new Rect(tr.x-3,y+8,tr.width+6,30),v,mn,mx);float t=Mathf.InverseLerp(mn,mx,nv);GUI.DrawTexture(new Rect(tr.x,y+18,tr.width*t,8),gold);GUI.DrawTexture(new Rect(tr.x+tr.width*t-10,y+10,20,20),gold);return nv;}
void Feedback(){Brand("F E E D B A C K");Rect p=new Rect(Screen.width*.28f,Screen.height*.27f,Screen.width*.44f,Screen.height*.46f);Panel(p);GUI.Label(new Rect(p.x+35,p.y+22,p.width-70,35),"YOUR FEEDBACK",lab);feedback=GUI.TextArea(new Rect(p.x+35,p.y+64,p.width-70,128),feedback,field);if(feedback.Length==0)GUI.Label(new Rect(p.x+48,p.y+76,p.width-96,35),"WRITE YOUR FEEDBACK HERE...",new GUIStyle(lab){fontSize=18});GUI.Label(new Rect(p.x+35,p.y+212,p.width-70,32),"EMAIL (OPTIONAL)",new GUIStyle(lab){fontSize=20});email=GUI.TextField(new Rect(p.x+35,p.y+245,p.width-70,48),email,field);GUI.Label(new Rect(p.x+35,p.y+310,p.width-70,32),"ISSUE TYPE",new GUIStyle(lab){fontSize=20});if(GUI.Button(new Rect(p.x+35,p.y+343,p.width-70,48),issues[issue]+"    ▼",field))issue=(issue+1)%issues.Length;Gold(new Rect(Screen.width/2-155,Screen.height*.75f,310,58),"SEND",()=>{PlayerPrefs.SetString("last_feedback",feedback);PlayerPrefs.SetString("last_feedback_email",email);PlayerPrefs.SetString("last_feedback_type",issues[issue]);PlayerPrefs.Save();msg="FEEDBACK SAVED";});Gold(new Rect(Screen.width/2-90,Screen.height*.84f,180,54),"BACK",()=>s=S.Menu);if(msg.Length>0)GUI.Label(new Rect(0,Screen.height*.92f,Screen.width,40),msg,Center(22));}
void Credits(){Brand("C R E D I T S");Rect p=new Rect(Screen.width*.24f,Screen.height*.31f,Screen.width*.52f,Screen.height*.42f);Panel(p);string[] a={"GAME DESIGN","PROGRAMMING","UI DESIGN","ENVIRONMENT ART","SOUND DESIGN","SPECIAL THANKS"},b={"YOU","YOU","YOU","YOU","YOU","THE PLAYERS"};for(int i=0;i<a.Length;i++){float y=p.y+42+i*56;GUI.Label(new Rect(p.x+80,y,280,38),a[i],lab);Line(new Rect(p.x+p.width*.43f,y+21,p.width*.17f,2));GUI.Label(new Rect(p.x+p.width-320,y,260,38),b[i],lab);}Gold(new Rect(Screen.width/2-85,Screen.height-82,170,56),"BACK",()=>s=S.Menu);}
void Game(){Brand("L E V E L  0");Panel(new Rect(Screen.width/2-300,Screen.height/2-110,600,220));GUI.Label(new Rect(Screen.width/2-260,Screen.height/2-65,520,100),msg.Length>0?msg:"LEVEL 0 LOADING",Center(30));Gold(new Rect(Screen.width/2-120,Screen.height/2+55,240,60),"MAIN MENU",()=>s=S.Menu);}
void Back(){if(s!=S.Menu){SavePrefs();s=S.Menu;}}
void Choice(Rect r,string t,Action a){GUI.Label(r,t,new GUIStyle(lab){fontSize=35,alignment=TextAnchor.MiddleLeft});Line(new Rect(r.x,r.y+r.height-12,r.width,2));GUI.DrawTexture(new Rect(r.x+r.width-8,r.y+r.height-16,8,8),gold);if(GUI.Button(r,"",Clear()))a();}
bool Gold(Rect r,string t,Action a){Border(r);bool c=GUI.Button(r,t,btn);if(c&&a!=null)a();return c;}
void Panel(Rect r){GUI.DrawTexture(r,panel);Border(r);Line(new Rect(r.x+2,r.y+2,r.width-4,2));}
void Border(Rect r){GUI.DrawTexture(new Rect(r.x,r.y,r.width,2),gold);GUI.DrawTexture(new Rect(r.x,r.yMax-2,r.width,2),gold);GUI.DrawTexture(new Rect(r.x,r.y,2,r.height),gold);GUI.DrawTexture(new Rect(r.xMax-2,r.y,2,r.height),gold);}
void Line(Rect r){GUI.DrawTexture(r,gold);}
void Glow(Rect r,string t,GUIStyle st){Color o=st.normal.textColor;st.normal.textColor=new Color(1f,.7f,.12f,.22f);GUI.Label(new Rect(r.x-3,r.y,r.width,r.height),t,st);GUI.Label(new Rect(r.x+3,r.y,r.width,r.height),t,st);GUI.Label(new Rect(r.x,r.y-3,r.width,r.height),t,st);GUI.Label(new Rect(r.x,r.y+3,r.width,r.height),t,st);st.normal.textColor=o;GUI.Label(r,t,st);}
GUIStyle Center(int z){GUIStyle g=new GUIStyle(lab){fontSize=z,alignment=TextAnchor.MiddleCenter,wordWrap=true};return g;}
GUIStyle Clear(){GUIStyle g=new GUIStyle(GUI.skin.button);g.normal.background=T(new Color(0,0,0,0));g.hover.background=g.normal.background;g.active.background=g.normal.background;g.normal.textColor=Color.clear;g.hover.textColor=Color.clear;g.active.textColor=Color.clear;return g;}
void Preview(Rect r,int i){GUI.DrawTexture(r,black);Border(r);GUI.DrawTexture(new Rect(r.x+r.width*.2f+i*4,r.y+10,40,r.height-20),dim);GUI.DrawTexture(new Rect(r.x+r.width*.55f,r.y+8,50,r.height-16),dim);GUI.DrawTexture(new Rect(r.x+20,r.y+30,r.width-40,14),gold);}
}
