using UnityEngine;
using System.Reflection;
using System.Collections.Generic;

public sealed class DesolationPolishPack : MonoBehaviour
{
    FirstPlayableBatch game; System.Type gt; GameObject p,e; Camera cam;
    Material wall, floor, metal, glow, dark, sign, stain;
    AudioSource hum, fx; AudioClip humC, footC, cueC, stingC, clickC;
    List<Renderer> renders = new List<Renderer>(); List<Light> flickers = new List<Light>();
    bool built, slotPanel; string ai="patrol"; Vector3 target, heard; float foot, cue, timer, bob, vol=.85f, look=1, scale=1; Texture2D px, grain;
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    static void Boot(){ if(!FindObjectOfType<DesolationPolishPack>()){var g=new GameObject("DesolationPolishPack");DontDestroyOnLoad(g);g.AddComponent<DesolationPolishPack>();}}
    void Start(){vol=PlayerPrefs.GetFloat("polish_volume",.85f);look=PlayerPrefs.GetFloat("polish_touch_look",1);scale=PlayerPrefs.GetFloat("polish_ui_scale",1);Tex();Mat();Audio();}
    bool Link(){ if(!game){game=FindObjectOfType<FirstPlayableBatch>(); if(!game)return false; gt=game.GetType();} p=Get<GameObject>("p"); e=Get<GameObject>("e"); cam=Get<Camera>("cam"); if(cam&&!hum){hum=cam.gameObject.AddComponent<AudioSource>();hum.clip=humC;hum.loop=true;hum.volume=.22f*vol;hum.Play();fx=cam.gameObject.AddComponent<AudioSource>();fx.volume=vol;} return p&&e&&cam;}
    T Get<T>(string n) where T:class{var f=gt.GetField(n,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic);return f==null?null:f.GetValue(game) as T;}
    object R(string n){var f=gt.GetField(n,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic);return f==null?null:f.GetValue(game);}
    void W(string n,object v){var f=gt.GetField(n,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic);if(f!=null)f.SetValue(game,v);}
    bool B(string n){var v=R(n);return v is bool && (bool)v;} float F(string n,float d=0){var v=R(n);return v is float?(float)v:d;} string State(){var v=R("s");return v==null?"":v.ToString();}
    void Tex(){px=new Texture2D(1,1);px.SetPixel(0,0,Color.black);px.Apply();grain=new Texture2D(32,32);for(int y=0;y<32;y++)for(int x=0;x<32;x++){float v=Random.Range(.25f,.75f);grain.SetPixel(x,y,new Color(v,v,v,.12f));}grain.Apply();}
    Material M(Color c,string tex="",float em=0){var sh=Shader.Find("Universal Render Pipeline/Lit");if(!sh)sh=Shader.Find("Standard");var m=new Material(sh);if(m.HasProperty("_Color"))m.color=c;if(m.HasProperty("_BaseColor"))m.SetColor("_BaseColor",c);var t=tex==""?null:Resources.Load<Texture2D>("Textures/"+tex);if(t){if(m.HasProperty("_MainTex"))m.mainTexture=t;if(m.HasProperty("_BaseMap"))m.SetTexture("_BaseMap",t);}if(em>0){m.EnableKeyword("_EMISSION");if(m.HasProperty("_EmissionColor"))m.SetColor("_EmissionColor",c*em);}return m;}
    void Mat(){wall=M(new Color(.55f,.48f,.2f),"wall_leak_color");floor=M(new Color(.18f,.12f,.05f),"carpet_fabric_color");metal=M(new Color(.23f,.23f,.22f),"painted_metal_color");glow=M(new Color(1,.78f,.2f),"office_ceiling_emission",1.5f);dark=M(new Color(.025f,.02f,.01f));sign=M(new Color(.9f,.68f,.18f),"plastic_panel_color",.25f);stain=M(new Color(.05f,.03f,.01f));}
    AudioClip Tone(string n,float sec,float hz,float a){int rate=22050,len=Mathf.RoundToInt(sec*rate);float[] d=new float[len];for(int i=0;i<len;i++){float t=i/(float)rate;d[i]=(Mathf.Sin(t*hz*6.283f)*a+Random.Range(-a,a)*.25f)*Mathf.Clamp01(1-t/sec);}var c=AudioClip.Create(n,len,1,rate,false);c.SetData(d,0);return c;}
    void Audio(){humC=Tone("fluorescent hum",5,70,.12f);footC=Tone("carpet footstep",.18f,95,.45f);cueC=Tone("entity cue",.6f,210,.45f);stingC=Tone("jumpscare stinger",.7f,300,.8f);clickC=Tone("ui click",.08f,520,.35f);}
    void Build(){if(built)return;built=true;RenderSettings.fog=true;RenderSettings.fogColor=new Color(.035f,.03f,.018f);RenderSettings.fogDensity=.045f;Room(new Vector3(-34,1,-34),10,7);Room(new Vector3(33,1,28),8,6);Room(new Vector3(-36,1,30),7,8);Room(new Vector3(30,1,-32),7,7);for(int i=0;i<28;i++){float x=-38+(i%8)*10,z=-36+(i/8)*24;Box("trim",new Vector3(x,.22f,z),new Vector3(6,.18f,.12f),metal,false);Box("outlet",new Vector3(x+1.4f,.55f,z+.15f),new Vector3(.18f,.25f,.05f),sign,false);if(i%3==0)Box("stain",new Vector3(x-1.5f,.02f,z+2),new Vector3(1.6f,.03f,.9f),stain,false);if(i%4==0)Box("sign",new Vector3(x+2,1.6f,z+.18f),new Vector3(1.1f,.55f,.06f),sign,false);if(i%5==0)Box("vent",new Vector3(x-2,.8f,z-.15f),new Vector3(1.2f,.35f,.07f),metal,false);}for(int i=0;i<10;i++){Vector3 v=new Vector3(Random.Range(-38,38),2.35f,Random.Range(-38,38));var l=new GameObject("flicker light").AddComponent<Light>();l.type=LightType.Point;l.color=new Color(1,.75f,.25f);l.range=Random.Range(5,9);l.intensity=.4f;l.transform.position=v;flickers.Add(l);Box("broken light",v,new Vector3(1.4f,.06f,.45f),i%3==0?dark:glow,false);}target=e.transform.position;foreach(var r in FindObjectsOfType<Renderer>())if(r)renders.Add(r);}
    void Room(Vector3 c,float w,float d){Box("modular floor",c+new Vector3(0,-.25f,0),new Vector3(w,.08f,d),floor,false);Box("wall",c+new Vector3(0,0,d*.5f),new Vector3(w,2.4f,.25f),wall,true);Box("wall",c+new Vector3(w*.5f,0,0),new Vector3(.25f,2.4f,d),wall,true);Box("wall",c+new Vector3(-w*.5f,0,0),new Vector3(.25f,2.4f,d),wall,true);Box("door frame",c+new Vector3(0,.15f,-d*.5f),new Vector3(2.2f,2.1f,.22f),metal,true);Box("rare prop",c+new Vector3(w*.25f,-.1f,d*.15f),Vector3.one*.65f,sign,true);}
    GameObject Box(string n,Vector3 p0,Vector3 s,Material m,bool col){var o=GameObject.CreatePrimitive(PrimitiveType.Cube);o.name=n;o.transform.position=p0;o.transform.localScale=s;o.GetComponent<Renderer>().material=m;if(!col)Destroy(o.GetComponent<Collider>());return o;}
    void Update(){if(!Link()||State()!="Game")return;Build();TouchAudio();Enemy();Cull();if(cam){bool mv=Input.GetAxisRaw("Horizontal")!=0||Input.GetAxisRaw("Vertical")!=0;if(mv)bob+=Time.deltaTime*6;cam.transform.localPosition=Vector3.Lerp(cam.transform.localPosition,new Vector3(Mathf.Sin(bob)*.025f,1.55f+Mathf.Abs(Mathf.Cos(bob))*.035f,0),Time.deltaTime*5);}}
    void TouchAudio(){bool mv=Input.GetAxisRaw("Horizontal")!=0||Input.GetAxisRaw("Vertical")!=0||p.transform.hasChanged;if(mv){heard=p.transform.position;foot-=Time.deltaTime;if(foot<=0&&fx){fx.PlayOneShot(footC,.45f*vol);foot=B("run")?.28f:.48f;}}float d=Vector3.Distance(e.transform.position,p.transform.position);if(d<13){cue-=Time.deltaTime;if(cue<=0&&fx){fx.PlayOneShot(cueC,Mathf.Lerp(.8f,.2f,d/13f)*vol);cue=1.2f;}}if(d<2.2f&&fx){fx.PlayOneShot(stingC,vol);}}
    bool See(){Vector3 a=e.transform.position+Vector3.up,b=p.transform.position+Vector3.up,d=b-a;if(d.magnitude>18||Vector3.Angle(e.transform.forward,d)>70)return false;RaycastHit h;if(Physics.Raycast(a,d.normalized,out h,d.magnitude-.2f))return h.collider.GetComponent<CharacterController>()!=null;return true;}
    bool Hide(){if(!B("hide"))return false;foreach(var o in FindObjectsOfType<GameObject>())if(o.name.ToLower().Contains("locker")&&Vector3.Distance(o.transform.position,p.transform.position)<2.8f)return !(Vector3.Distance(e.transform.position,p.transform.position)<4&&See());return false;}
    void Enemy(){bool safe=Hide(),see=See()&&!safe,hear=heard!=Vector3.zero&&Vector3.Distance(heard,e.transform.position)<14&&!safe;if(see){ai="chase";target=p.transform.position;timer=6;}else if(hear){ai="investigate";target=heard;heard=Vector3.zero;timer=4;}else if(B("dec")){ai="investigate";target=p.transform.position+p.transform.forward*6;timer=4;}else if(timer>0)timer-=Time.deltaTime;else if(ai=="chase")ai="search";else if(ai=="search")ai="give up";else if(ai=="give up")ai="patrol";if(ai=="patrol"&&Vector3.Distance(e.transform.position,target)<1.2f)target=new Vector3(Random.Range(-30,30),1,Random.Range(-30,30));Vector3 v=target-e.transform.position;v.y=0;float sp=ai=="chase"?3.4f:ai=="search"?2.1f:1.4f;if(v.sqrMagnitude>.1f){e.transform.rotation=Quaternion.Slerp(e.transform.rotation,Quaternion.LookRotation(v.normalized),Time.deltaTime*5);e.transform.position+=v.normalized*sp*Time.deltaTime;}if(Vector3.Distance(e.transform.position,p.transform.position)<2&&!safe){ai="attack";W("hp",Mathf.Max(0,F("hp",100)-Time.deltaTime*12));W("sa",Mathf.Max(0,F("sa",100)-Time.deltaTime*10));}}
    void Cull(){Vector3 cp=cam.transform.position,cf=cam.transform.forward;foreach(var r in renders){if(!r||r.transform.IsChildOf(p.transform)||r.gameObject==e)continue;Vector3 to=r.bounds.center-cp;float d=to.magnitude,dot=Vector3.Dot(cf,to.normalized);bool ground=r.name.ToLower().Contains("floor")||r.name.ToLower().Contains("ceiling");r.enabled=d<7||(dot>-.05f&&d<44)||(ground&&dot>.2f&&d<28);}foreach(var l in flickers)if(l)l.intensity=Mathf.Lerp(.05f,.75f,Mathf.PerlinNoise(l.transform.position.x,Time.time*3));}
    void OnGUI(){if(!Link())return;string st=State();if(st=="Game"){GUI.color=new Color(0,0,0,.22f);GUI.DrawTexture(new Rect(0,0,Screen.width,72),px);GUI.DrawTexture(new Rect(0,Screen.height-80,Screen.width,80),px);GUI.color=new Color(1,1,1,.055f);GUI.DrawTexture(new Rect(0,0,Screen.width,Screen.height),grain);GUI.color=Color.white;GUI.Label(new Rect(25,170,760,30),"AI "+ai.ToUpper()+" | level polish, audio polish, visual polish, high culling");}else if(st=="Menu"){if(GUI.Button(new Rect(Screen.width-270,110,240,56),slotPanel?"CLOSE SLOT PREVIEWS":"SAVE SLOT PREVIEWS",s)){slotPanel=!slotPanel;if(fx)fx.PlayOneShot(clickC,.6f*vol);}if(slotPanel)Slots();}else if(st=="Settings")Settings();}
    void Slots(){GUI.DrawTexture(new Rect(Screen.width-445,185,410,315),px);for(int i=0;i<3;i++){float y=210+i*88;GUI.Label(new Rect(Screen.width-415,y,270,54),"Slot "+(i+1)+" preview\n"+PlayerPrefs.GetString("polish_slot_"+i,"Ready"));if(GUI.Button(new Rect(Screen.width-145,y,90,42),"SAVE",s)){PlayerPrefs.SetString("polish_slot_"+i,"AI "+ai+" / "+System.DateTime.Now.ToString("HH:mm"));PlayerPrefs.Save();}}}
    void Settings(){GUI.DrawTexture(new Rect(65,150,450,330),px);GUI.Label(new Rect(90,170,390,45),"Polish settings");GUI.Label(new Rect(90,230,160,30),"Touch look");look=GUI.HorizontalSlider(new Rect(245,238,220,22),look,.35f,2.5f);GUI.Label(new Rect(90,275,160,30),"UI scale");scale=GUI.HorizontalSlider(new Rect(245,283,220,22),scale,.8f,1.55f);GUI.Label(new Rect(90,320,160,30),"Audio");vol=GUI.HorizontalSlider(new Rect(245,328,220,22),vol,0,1);if(GUI.Button(new Rect(130,385,300,50),"SAVE POLISH SETTINGS",s)){PlayerPrefs.SetFloat("polish_volume",vol);PlayerPrefs.SetFloat("polish_touch_look",look);PlayerPrefs.SetFloat("polish_ui_scale",scale);PlayerPrefs.Save();if(hum)hum.volume=.22f*vol;}}
}
