using System.Collections.Generic;
using UnityEngine;
public sealed class DesolationRuntime:MonoBehaviour{
enum M{Title,Game,Pause,Settings,Help,End}
class I{public string id,k,t;public GameObject g;}
M mode=M.Title;List<I> items=new List<I>();HashSet<string> used=new HashSet<string>(),notes=new HashSet<string>();Dictionary<string,Material> mat=new Dictionary<string,Material>();
GameObject world,pl,enemy,door;CharacterController cc;Camera cam;Vector3 vel,last,lure;Vector2 mv;float yaw,pitch,st=1,sa=1,hide,msgt,sens=1,vol=.8f,bs=1,lureT;int slot,fuses,scraps=2;bool breaker,lureOn,sprint;string msg="",ending="";GUIStyle big,txt,btn;
void Start(){Application.targetFrameRate=60;Screen.sleepTimeout=SleepTimeout.NeverSleep;sens=PlayerPrefs.GetFloat("u_sens",1);vol=PlayerPrefs.GetFloat("u_vol",.8f);bs=PlayerPrefs.GetFloat("u_bs",1);AudioListener.volume=vol;var c=new GameObject("MenuCamera").AddComponent<Camera>();c.clearFlags=CameraClearFlags.SolidColor;c.backgroundColor=new Color(.02f,.015f,.006f);c.transform.position=new Vector3(0,0,-10);}
string K(string x){return"slot_"+slot+"_"+x;}bool Has(int s){return PlayerPrefs.GetInt("slot_"+s+"_saved",0)==1;}
void NewGame(int s,bool load){slot=s;if(world)Destroy(world);used.Clear();notes.Clear();items.Clear();fuses=0;scraps=2;sa=1;st=1;breaker=false;yaw=0;pitch=0;if(load){fuses=PlayerPrefs.GetInt(K("f"),0);scraps=PlayerPrefs.GetInt(K("sc"),2);sa=PlayerPrefs.GetFloat(K("sa"),1);breaker=PlayerPrefs.GetInt(K("br"),0)==1;foreach(var x in PlayerPrefs.GetString(K("u"),"").Split('|'))if(x.Length>0)used.Add(x);foreach(var x in PlayerPrefs.GetString(K("n"),"").Split('|'))if(x.Length>0)notes.Add(x);}Build();if(load){pl.transform.position=new Vector3(PlayerPrefs.GetFloat(K("x"),0),.9f,PlayerPrefs.GetFloat(K("z"),0));yaw=PlayerPrefs.GetFloat(K("yaw"),0);OpenDoor();}mode=M.Game;Save();Say("Find 3 fuses. Read 5 notes. Hide, throw scraps, escape.",4);}
void Save(){if(!pl)return;PlayerPrefs.SetInt(K("saved"),1);PlayerPrefs.SetFloat(K("x"),pl.transform.position.x);PlayerPrefs.SetFloat(K("z"),pl.transform.position.z);PlayerPrefs.SetFloat(K("yaw"),yaw);PlayerPrefs.SetInt(K("f"),fuses);PlayerPrefs.SetInt(K("sc"),scraps);PlayerPrefs.SetFloat(K("sa"),sa);PlayerPrefs.SetInt(K("br"),breaker?1:0);PlayerPrefs.SetString(K("u"),string.Join("|",new List<string>(used).ToArray()));PlayerPrefs.SetString(K("n"),string.Join("|",new List<string>(notes).ToArray()));PlayerPrefs.Save();}
void Build(){world=new GameObject("DesolationLevelZero");Mat();RenderSettings.fog=true;RenderSettings.fogDensity=.035f;RenderSettings.fogColor=new Color(.08f,.07f,.04f);Room(Vector3.zero,16,16,"wall");Room(new Vector3(16,0,-4),18,12,"bad");Room(new Vector3(-14,0,8),14,12,"wall");Room(new Vector3(4,0,20),14,12,"bad");Room(new Vector3(22,0,18),12,16,"wall");for(int i=0;i<18;i++)Box(new Vector3(-16+i%6*7,1.2f,-14+i/6*11),new Vector3(.7f,2.4f,.7f),"bad",1);for(int i=0;i<7;i++)Light(new Vector3(-10+i*6,2.5f,-8+(i%2)*14));Fuse("f1",-5,-5);Fuse("f2",19,-8);Fuse("f3",-18,11);Note("n1",0,-7,"BLUE power opens the exit.");Note("n2",-19,6,"Stained walls hide breathing.");Note("n3",18,-9,"Throw scraps to distract it.");Note("n4",5,22,"The breaker unlocks maintenance.");Note("n5",25,16,"Truth needs all notes and sanity.");Add("h1","hide","Hide in stained wallpaper",Box(new Vector3(-9,.9f,-7),new Vector3(1.2f,1.3f,.7f),"bad",1));Add("h2","hide","Hide in stained wallpaper",Box(new Vector3(-19,.9f,9),new Vector3(1.2f,1.3f,.7f),"bad",1));Add("radio","radio","Take metal scraps",Box(new Vector3(2,.5f,18),Vector3.one*.6f,"metal",0));Add("breaker","breaker","Switch breaker",Box(new Vector3(-20,1,11),new Vector3(.7f,.8f,.3f),"metal",0));door=Box(new Vector3(-8,1.2f,8),new Vector3(.3f,2.2f,3.2f),"metal",1);Add("door","door","Locked service door",door);Add("exit","exit","Service exit",Box(new Vector3(26,1.1f,21),new Vector3(.3f,2.2f,2.4f),"metal",1));Player();Enemy();OpenDoor();}
void Mat(){mat["wall"]=Ma(.72f,.63f,.25f);mat["bad"]=Ma(.48f,.42f,.17f);mat["floor"]=Ma(.32f,.24f,.12f);mat["ceil"]=Ma(.58f,.56f,.42f);mat["metal"]=Ma(.2f,.2f,.18f);mat["blue"]=Ma(0,.8f,1);mat["dark"]=Ma(.01f,.01f,.01f);mat["wood"]=Ma(.32f,.2f,.1f);}
Material Ma(float r,float g,float b){var m=new Material(Shader.Find("Standard"));m.color=new Color(r,g,b);return m;}
void Room(Vector3 c,float x,float z,string w){Box(c+new Vector3(0,-.05f,0),new Vector3(x,.1f,z),"floor",1);Box(c+new Vector3(0,2.6f,0),new Vector3(x,.1f,z),"ceil",0);Box(c+new Vector3(0,1.2f,z/2),new Vector3(x,2.5f,.2f),w,1);Box(c+new Vector3(0,1.2f,-z/2),new Vector3(x,2.5f,.2f),w,1);Box(c+new Vector3(x/2,1.2f,0),new Vector3(.2f,2.5f,z),w,1);Box(c+new Vector3(-x/2,1.2f,0),new Vector3(.2f,2.5f,z),w,1);}
GameObject Box(Vector3 p,Vector3 s,string mt,int col){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.transform.SetParent(world.transform);g.transform.position=p;g.transform.localScale=s;g.GetComponent<Renderer>().material=mat[mt];if(col==0)Destroy(g.GetComponent<Collider>());return g;}
void Light(Vector3 p){var l=new GameObject("light").AddComponent<Light>();l.transform.SetParent(world.transform);l.transform.position=p;l.type=LightType.Point;l.range=8;l.intensity=.65f;Box(p,new Vector3(2,.06f,.4f),"ceil",0);}
void Fuse(string id,float x,float z){if(!used.Contains(id))Add(id,"fuse","Collect blue fuse",Box(new Vector3(x,.5f,z),Vector3.one*.45f,"blue",0));}
void Note(string id,float x,float z,string t){if(!used.Contains(id))Add(id,"note",t,Box(new Vector3(x,.7f,z),new Vector3(.8f,.08f,.5f),"wood",0));}
void Add(string id,string k,string t,GameObject g){g.name=id;items.Add(new I{id=id,k=k,t=t,g=g});}
void Player(){pl=new GameObject("Player");pl.transform.SetParent(world.transform);pl.transform.position=new Vector3(0,.9f,0);cc=pl.AddComponent<CharacterController>();cc.height=1.75f;cc.radius=.32f;var co=new GameObject("Camera");co.transform.SetParent(pl.transform);co.transform.localPosition=new Vector3(0,.65f,0);cam=co.AddComponent<Camera>();co.AddComponent<AudioListener>();}
void Enemy(){enemy=GameObject.CreatePrimitive(PrimitiveType.Capsule);enemy.transform.SetParent(world.transform);enemy.transform.position=new Vector3(13,.9f,12);enemy.GetComponent<Renderer>().material=mat["dark"];Destroy(enemy.GetComponent<Collider>());last=pl.transform.position;}
void Update(){if(mode!=M.Game)return;InputGame();Move();AI();if(msgt>0)msgt-=Time.deltaTime;}
void InputGame(){mv=Vector2.zero;sprint=Input.GetKey(KeyCode.LeftShift);if(Input.GetKey(KeyCode.W))mv.y++;if(Input.GetKey(KeyCode.S))mv.y--;if(Input.GetKey(KeyCode.A))mv.x--;if(Input.GetKey(KeyCode.D))mv.x++;yaw+=Input.GetAxis("Mouse X")*4*sens;pitch=Mathf.Clamp(pitch-Input.GetAxis("Mouse Y")*3*sens,-80,80);if(Input.GetKeyDown(KeyCode.E))Use();if(Input.GetKeyDown(KeyCode.F))Throw();if(Input.GetKeyDown(KeyCode.Escape)||Input.GetKeyDown(KeyCode.Backspace))mode=M.Pause;}
void Move(){pl.transform.rotation=Quaternion.Euler(0,yaw,0);cam.transform.localRotation=Quaternion.Euler(pitch,0,0);var d=pl.transform.right*mv.x+pl.transform.forward*mv.y;float sp=sprint&&st>.05f?5.2f:3.4f;st=Mathf.Clamp01(st+((sprint&&d.sqrMagnitude>.01f)?-.16f:.18f)*Time.deltaTime);vel.x=d.x*sp;vel.z=d.z*sp;vel.y=cc.isGrounded?-.1f:vel.y-18*Time.deltaTime;cc.Move(vel*Time.deltaTime);}
void AI(){bool hidden=Time.time<hide;bool sees=CanSee()&&!hidden;if(sees)last=pl.transform.position;Vector3 target=lureOn&&Time.time<lureT?lure:last;if(lureOn&&Time.time>=lureT)lureOn=false;var d=target-enemy.transform.position;d.y=0;if(d.magnitude>.2f)enemy.transform.position+=d.normalized*(sees?2.1f:1.2f)*Time.deltaTime;float dist=Vector3.Distance(enemy.transform.position,pl.transform.position);if(dist<5&&!hidden)sa-=Time.deltaTime*(sees?.09f:.03f);else sa=Mathf.Min(1,sa+Time.deltaTime*.015f);if(dist<1.2f&&!hidden)End("lost");if(sa<=0)End("desolation");}
bool CanSee(){Vector3 a=enemy.transform.position+Vector3.up,b=pl.transform.position+Vector3.up;if(Vector3.Distance(a,b)>18)return false;RaycastHit h;if(!Physics.Raycast(a,(b-a).normalized,out h,Vector3.Distance(a,b)))return true;return h.collider&&h.collider.GetComponentInParent<CharacterController>()==cc;}
I Near(){I best=null;float bd=2.3f;foreach(var t in items){if(!t.g)continue;float d=Vector3.Distance(pl.transform.position,t.g.transform.position);if(d<bd){bd=d;best=t;}}return best;}
void Use(){var t=Near();if(t==null){Say("Nothing close.",1);return;}if(t.k=="fuse"){fuses++;used.Add(t.id);items.Remove(t);Destroy(t.g);Say("Fuse "+fuses+"/3",2);}else if(t.k=="note"){used.Add(t.id);notes.Add(t.id);items.Remove(t);Destroy(t.g);Say(t.t,4);}else if(t.k=="hide"){hide=Time.time+3.5f;sa=Mathf.Min(1,sa+.12f);Say("You hide and breathe slowly.",2);}else if(t.k=="breaker"){breaker=true;OpenDoor();Say("Breaker online.",2);}else if(t.k=="radio"){scraps+=2;items.Remove(t);Destroy(t.g);Say("Scraps collected.",2);}else if(t.k=="door")Say(breaker?"Door open.":"Locked. Find breaker.",2);else if(t.k=="exit"){if(fuses<3)Say("Exit needs three fuses.",2);else if(notes.Count>=5&&sa>.4f)End("truth");else if(sa<.28f)End("desolation");else End("escape");}Save();}
void Throw(){if(scraps<=0){Say("No scraps.",1);return;}scraps--;lure=pl.transform.position+pl.transform.forward*7;lureOn=true;lureT=Time.time+5;Say("Metal clatters away.",2);}
void OpenDoor(){if(!breaker||!door)return;var c=door.GetComponent<Collider>();if(c)c.enabled=false;}
void End(string k){mode=M.End;if(k=="truth")ending="TRUTH ENDING\nYou read every clue and escaped with proof.";else if(k=="lost")ending="LOST ENDING\nIt found your steps.";else if(k=="desolation")ending="DESOLATION ENDING\nThe rooms learned your shape.";else ending="ESCAPE ENDING\nYou powered the exit and escaped.";Save();}
void Say(string x,float t){msg=x;msgt=t;}
void OnGUI(){if(big==null){big=new GUIStyle(GUI.skin.label){fontSize=48,alignment=TextAnchor.MiddleCenter};txt=new GUIStyle(GUI.skin.label){fontSize=22,wordWrap=true};btn=new GUIStyle(GUI.skin.button){fontSize=22};}if(mode==M.Title){GUI.Label(new Rect(0,50,Screen.width,80),"DESOLATION: THE BACKROOMS",big);for(int i=0;i<3;i++)if(GUI.Button(new Rect(Screen.width/2-220,180+i*65,440,56),Has(i)?"CONTINUE SLOT "+(i+1):"NEW GAME SLOT "+(i+1),btn))NewGame(i,Has(i));if(GUI.Button(new Rect(Screen.width/2-220,390,440,56),"SETTINGS",btn))mode=M.Settings;if(GUI.Button(new Rect(Screen.width/2-220,455,440,56),"APK HELP",btn))mode=M.Help;}else if(mode==M.Game){GUI.Label(new Rect(20,20,1000,40),"Fuses "+fuses+"/3  Notes "+notes.Count+"/5  Scraps "+scraps+"  Sanity "+Mathf.RoundToInt(sa*100)+"%",txt);var n=Near();GUI.Label(new Rect(20,60,1000,70),msgt>0?msg:n!=null?"USE: "+n.t:"",txt);if(GUI.Button(new Rect(40,Screen.height-90,170*bs,60*bs),"USE",btn))Use();if(GUI.Button(new Rect(Screen.width-210,Screen.height-90,170*bs,60*bs),"THROW",btn))Throw();if(GUI.Button(new Rect(Screen.width-130,20,110,55),"MENU",btn))mode=M.Pause;}else if(mode==M.Pause){if(GUI.Button(new Rect(Screen.width/2-200,220,400,60),"RESUME",btn))mode=M.Game;if(GUI.Button(new Rect(Screen.width/2-200,290,400,60),"SAVE",btn))Save();if(GUI.Button(new Rect(Screen.width/2-200,360,400,60),"MAIN MENU",btn)){mode=M.Title;if(world)world.SetActive(false);}}else if(mode==M.Settings){GUI.Label(new Rect(120,80,700,50),"Sensitivity / Volume / Button Size",txt);sens=GUI.HorizontalSlider(new Rect(120,140,600,40),sens,.4f,2);vol=GUI.HorizontalSlider(new Rect(120,200,600,40),vol,0,1);bs=GUI.HorizontalSlider(new Rect(120,260,600,40),bs,.75f,1.35f);if(GUI.Button(new Rect(120,330,300,60),"SAVE",btn)){PlayerPrefs.SetFloat("u_sens",sens);PlayerPrefs.SetFloat("u_vol",vol);PlayerPrefs.SetFloat("u_bs",bs);PlayerPrefs.Save();AudioListener.volume=vol;mode=M.Title;}}else if(mode==M.Help){GUI.Label(new Rect(80,100,Screen.width-160,250),"Android installs .apk directly. If you download .apk.7z, extract it first, then install the extracted APK.",txt);if(GUI.Button(new Rect(Screen.width/2-160,400,320,60),"BACK",btn))mode=M.Title;}else if(mode==M.End){GUI.Label(new Rect(80,120,Screen.width-160,240),ending,txt);if(GUI.Button(new Rect(Screen.width/2-200,390,400,60),"MAIN MENU",btn))mode=M.Title;}}
void OnApplicationPause(bool pz){if(pz)Save();}void OnApplicationQuit(){Save();}
}