using UnityEngine;using System.Reflection;
public sealed class DesolationFeatureBatch:MonoBehaviour{
FirstPlayableBatch r;System.Type t;GameObject p,e;Camera c;GUIStyle s;Texture2D bg;float touch=1,ui=1;string ai="PATROL";Vector3 target,heard;bool slots;
[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){if(!FindObjectOfType<DesolationFeatureBatch>()){var g=new GameObject("DesolationFeatureBatch");DontDestroyOnLoad(g);g.AddComponent<DesolationFeatureBatch>();}}
void Start(){touch=PlayerPrefs.GetFloat("df_touch",1);ui=PlayerPrefs.GetFloat("df_ui",1);bg=new Texture2D(1,1);bg.SetPixel(0,0,new Color(0,0,0,.8f));bg.Apply();s=new GUIStyle(GUI.skin.button){fontSize=22,fontStyle=FontStyle.Bold};}
bool Link(){if(!r){r=FindObjectOfType<FirstPlayableBatch>();if(!r)return false;t=r.GetType();}p=G<GameObject>("p");e=G<GameObject>("e");c=G<Camera>("cam");return p&&e&&c;}
T G<T>(string n)where T:class{var f=t.GetField(n,BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public);return f==null?null:f.GetValue(r)as T;}object V(string n){var f=t.GetField(n,BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public);return f==null?null:f.GetValue(r);}void W(string n,object v){var f=t.GetField(n,BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public);if(f!=null)f.SetValue(r,v);}bool B(string n){var v=V(n);return v is bool&&(bool)v;}float F(string n){var v=V(n);return v is float?(float)v:0;}string St(){var v=V("s");return v==null?"":v.ToString();}
void LateUpdate(){if(!Link()||St()!="Game")return;Touch();Enemy();Cull();}
void Touch(){for(int i=0;i<Input.touchCount;i++){var q=Input.GetTouch(i);if(q.position.x>Screen.width*.5f&&q.phase==TouchPhase.Moved){float y=F("yaw")+q.deltaPosition.x*touch*.08f,pit=Mathf.Clamp(F("pit")-q.deltaPosition.y*touch*.08f,-70,70);W("yaw",y);W("pit",pit);p.transform.rotation=Quaternion.Euler(0,y,0);c.transform.localRotation=Quaternion.Euler(pit,0,0);}if(q.position.x<Screen.width*.45f&&q.phase==TouchPhase.Moved){var cc=p.GetComponent<CharacterController>();if(!cc)return;Vector2 v=Vector2.ClampMagnitude(q.deltaPosition/(45f*ui),1);Vector3 m=p.transform.right*v.x+p.transform.forward*v.y;m.y=-9.8f;cc.Move(m*2.6f*Time.deltaTime);if(v.magnitude>.45f)heard=p.transform.position;}}}
bool See(){Vector3 a=e.transform.position+Vector3.up,b=p.transform.position+Vector3.up,d=b-a;if(d.magnitude>18||Vector3.Angle(e.transform.forward,d)>70)return false;RaycastHit h;if(Physics.Raycast(a,d.normalized,out h,d.magnitude-.2f)&&!h.collider.GetComponent<CharacterController>())return false;return true;}
void Enemy(){bool safe=false;foreach(var o in FindObjectsOfType<GameObject>())if(o.name.Contains("locker")&&Vector3.Distance(o.transform.position,p.transform.position)<2.7f&&B("hide"))safe=true;bool see=See()&&!safe,hear=heard!=Vector3.zero&&Vector3.Distance(heard,e.transform.position)<14&&!safe;if(see){ai="CHASE";target=p.transform.position;}else if(hear||B("dec")){ai="INVESTIGATE";target=hear?heard:p.transform.position+p.transform.forward*6;heard=Vector3.zero;}else if(ai=="CHASE")ai="SEARCH";else if(ai=="SEARCH")ai="GIVE UP";else if(ai=="GIVE UP")ai="PATROL";if(ai=="PATROL"&&Vector3.Distance(e.transform.position,target)<1)target=new Vector3(Random.Range(-30,30),1,Random.Range(-30,30));Vector3 v=target-e.transform.position;v.y=0;float sp=ai=="CHASE"?3.4f:ai=="SEARCH"?2.1f:1.4f;if(v.sqrMagnitude>.1f){e.transform.rotation=Quaternion.Slerp(e.transform.rotation,Quaternion.LookRotation(v.normalized),Time.deltaTime*5);e.transform.position+=v.normalized*sp*Time.deltaTime;}if(Vector3.Distance(e.transform.position,p.transform.position)<2&&!safe){W("hp",Mathf.Max(0,F("hp")-Time.deltaTime*12));W("sa",Mathf.Max(0,F("sa")-Time.deltaTime*10));ai="ATTACK";}}
void Cull(){foreach(var rr in FindObjectsOfType<Renderer>()){if(!rr||rr.transform.IsChildOf(p.transform)||rr.gameObject==e)continue;Vector3 to=rr.bounds.center-c.transform.position;float d=to.magnitude,dot=Vector3.Dot(c.transform.forward,to.normalized);bool ground=rr.name.Contains("floor")||rr.name.Contains("ceiling");rr.enabled=d<7||(dot>-.05f&&d<42)||(ground&&dot>.2f&&d<26);}}
void OnGUI(){if(!Link())return;string st=St();if(st=="Game"){GUI.Label(new Rect(25,170,600,30),"AI "+ai+"  HIGH CULLING ACTIVE");}if(st=="Menu"){if(GUI.Button(new Rect(Screen.width-255,120,220,55),slots?"CLOSE SLOTS":"SAVE PREVIEWS",s))slots=!slots;if(slots){GUI.DrawTexture(new Rect(Screen.width-430,190,390,320),bg);for(int i=0;i<3;i++){float y=215+i*88;GUI.Label(new Rect(Screen.width-405,y,250,50),"Slot "+(i+1)+" preview\n"+PlayerPrefs.GetString("df_slot_"+i,"Ready"));if(GUI.Button(new Rect(Screen.width-155,y,90,42),"SAVE",s)){PlayerPrefs.SetString("df_slot_"+i,"AI "+ai);PlayerPrefs.Save();}}}}if(st=="Settings"){GUI.DrawTexture(new Rect(65,150,430,260),bg);GUI.Label(new Rect(85,165,380,55),"Touch-look and accessibility scale");touch=GUI.HorizontalSlider(new Rect(190,245,250,25),touch,.35f,2.5f);ui=GUI.HorizontalSlider(new Rect(190,290,250,25),ui,.8f,1.55f);if(GUI.Button(new Rect(130,335,280,45),"SAVE MOBILE SETTINGS",s)){PlayerPrefs.SetFloat("df_touch",touch);PlayerPrefs.SetFloat("df_ui",ui);PlayerPrefs.Save();}}}
}