using UnityEngine;
public class BatchOneGame:MonoBehaviour{
enum P{M,G,P,E}P p;Camera c;CharacterController cc;GameObject pl,en;GUIStyle s,b;Texture2D g,d;int f;float hp=100,san=100,st=100,yaw,pit;bool key,pow,run,use,hide;string msg="",end="";
[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){if(FindObjectOfType<BatchOneGame>())return;var o=new GameObject("BatchOneGame");DontDestroyOnLoad(o);o.AddComponent<BatchOneGame>();}
void Awake(){foreach(var r in FindObjectsOfType<DesolationRuntime>())r.enabled=false;}
void Start(){g=T(new Color(1,.78f,.16f,.95f));d=T(new Color(0,0,0,.7f));s=new GUIStyle(GUI.skin.label){fontSize=24,fontStyle=FontStyle.Bold,wordWrap=true};s.normal.textColor=new Color(1,.82f,.3f);b=new GUIStyle(GUI.skin.button){fontSize=24,fontStyle=FontStyle.Bold};b.normal.textColor=new Color(1,.82f,.3f);Build();Menu();}
Texture2D T(Color c){var t=new Texture2D(1,1);t.SetPixel(0,0,c);t.Apply();return t;}
Material M(Color c){var m=new Material(Shader.Find("Standard"));m.color=c;return m;}
GameObject C(string n,Vector3 p,Vector3 z,Material m){var o=GameObject.CreatePrimitive(PrimitiveType.Cube);o.name=n;o.transform.position=p;o.transform.localScale=z;o.GetComponent<Renderer>().material=m;return o;}
void Build(){var wall=M(new Color(.55f,.48f,.18f));var floor=M(new Color(.16f,.11f,.05f));var glow=M(new Color(1,.78f,.16f));C("floor",new Vector3(0,-.1f,0),new Vector3(70,.2f,70),floor);for(int i=-8;i<=8;i++){C("wall",new Vector3(i*4,1.2f,-34),new Vector3(4,2.4f,.3f),wall);C("wall",new Vector3(i*4,1.2f,34),new Vector3(4,2.4f,.3f),wall);C("wall",new Vector3(-34,1.2f,i*4),new Vector3(.3f,2.4f,4),wall);C("wall",new Vector3(34,1.2f,i*4),new Vector3(.3f,2.4f,4),wall);if(i%2==0)C("pillar",new Vector3(i*3,1.2f,i*2),new Vector3(1,2.4f,1),wall);}Add("fuse",new Vector3(-12,.5f,-10),glow);Add("fuse",new Vector3(8,.5f,-14),glow);Add("fuse",new Vector3(-6,.5f,16),glow);Add("key",new Vector3(20,.5f,-20),glow);Add("breaker",new Vector3(22,1,-5),wall);Add("exit",new Vector3(30,1,28),wall);Add("locker",new Vector3(-18,1,8),wall);pl=new GameObject("Player");cc=pl.AddComponent<CharacterController>();cc.height=1.7f;cc.radius=.3f;c=new GameObject("Camera").AddComponent<Camera>();c.gameObject.AddComponent<AudioListener>();c.transform.SetParent(pl.transform);c.transform.localPosition=new Vector3(0,1.5f,0);en=GameObject.CreatePrimitive(PrimitiveType.Capsule);en.name="Entity";en.transform.position=new Vector3(20,1,20);en.GetComponent<Renderer>().material=M(Color.black);Destroy(en.GetComponent<Collider>());}
void Add(string n,Vector3 p,Material m){var o=C(n,p,new Vector3(.7f,.7f,.7f),m);if(n=="fuse"||n=="key")o.GetComponent<Collider>().isTrigger=true;}
void Menu(){p=P.M;pl.SetActive(false);en.SetActive(false);c.transform.SetParent(null);c.transform.position=new Vector3(0,1.6f,-9);c.transform.rotation=Quaternion.Euler(5,0,0);Cursor.lockState=CursorLockMode.None;Cursor.visible=true;}
void StartRun(){p=P.G;pl.SetActive(true);en.SetActive(true);pl.transform.position=new Vector3(-24,1,-24);f=0;key=pow=false;hp=san=st=100;Cursor.lockState=CursorLockMode.Locked;Cursor.visible=false;}
void Update(){if(Input.GetKeyDown(KeyCode.Escape))Back();if(p!=P.G)return;Move();Near();AI();if(hp<=0||san<=0)End("CONSUMED");run=use=hide=false;}
void Move(){var mv=new Vector2(Input.GetAxisRaw("Horizontal"),Input.GetAxisRaw("Vertical"));float sp=(Input.GetKey(KeyCode.LeftShift)||run)?4.5f:2.5f;var m=pl.transform.right*mv.x+pl.transform.forward*mv.y;m=Vector3.ClampMagnitude(m,1)*sp;m.y=-9.8f;cc.Move(m*Time.deltaTime);yaw+=Input.GetAxis("Mouse X")*3;pit=Mathf.Clamp(pit-Input.GetAxis("Mouse Y")*3,-70,70);pl.transform.rotation=Quaternion.Euler(0,yaw,0);c.transform.localRotation=Quaternion.Euler(pit,0,0);st=Mathf.Clamp(st+Time.deltaTime*10-(sp>3?Time.deltaTime*25:0),0,100);}
void Near(){hide=false;foreach(var o in FindObjectsOfType<GameObject>()){if(Vector3.Distance(pl.transform.position,o.transform.position)>2.6f)continue;if(o.name=="locker"&&(Input.GetKey(KeyCode.C)||hide)){hide=true;san=Mathf.Min(100,san+Time.deltaTime*5);}if(!(Input.GetKeyDown(KeyCode.E)||use))continue;if(o.name=="fuse"){f++;Destroy(o);msg="FUSE "+f+"/3";}else if(o.name=="key"){key=true;Destroy(o);msg="KEY";}else if(o.name=="breaker"){if(f>=3&&key){pow=true;msg="POWERED";}else msg="NEED FUSES AND KEY";}else if(o.name=="exit"){if(pow)End(san>50?"ESCAPED":"HOLLOW ESCAPE");else msg="POWER EXIT FIRST";}}}
void AI(){var e=en.transform.position;var pp=pl.transform.position;bool ch=Vector3.Distance(e,pp)<15&&!hide;var t=ch?pp:new Vector3(Mathf.Sin(Time.time*.2f)*24,1,Mathf.Cos(Time.time*.18f)*24);var d0=t-e;d0.y=0;if(d0.sqrMagnitude>.2f){en.transform.rotation=Quaternion.LookRotation(d0.normalized);en.transform.position+=d0.normalized*(ch?3.2f:1.4f)*Time.deltaTime;}if(Vector3.Distance(en.transform.position,pp)<2&&!hide){hp-=Time.deltaTime*25;san-=Time.deltaTime*18;}else if(ch)san-=Time.deltaTime*6;}
void End(string e){end=e;p=P.E;Cursor.lockState=CursorLockMode.None;Cursor.visible=true;}
void Back(){if(p==P.G){p=P.P;Cursor.lockState=CursorLockMode.None;Cursor.visible=true;}else if(p==P.P){p=P.G;Cursor.lockState=CursorLockMode.Locked;Cursor.visible=false;}else Menu();}
void OnGUI(){GUI.DrawTexture(new Rect(0,0,Screen.width,Screen.height),d);if(p==P.M){Title("DESOLATION: THE BACKROOMS");if(GUI.Button(new Rect(70,220,260,70),"PLAY",b))StartRun();if(GUI.Button(new Rect(70,310,260,70),"STATUS",b))msg="Batch 1: playable loop, enemy, hiding, HUD";}else if(p==P.G){GUI.Label(new Rect(20,20,500,40),f<3?"Find fuses "+f+"/3":!key?"Find key":!pow?"Power breaker":"Escape",s);Bar(20,70,hp,"HEALTH");Bar(20,100,san,"SANITY");GUI.Label(new Rect(0,150,Screen.width,40),msg,s);if(GUI.Button(new Rect(Screen.width-160,Screen.height-160,130,55),"USE",b))use=true;if(GUI.RepeatButton(new Rect(Screen.width-310,Screen.height-160,130,55),"SPRINT",b))run=true;if(GUI.RepeatButton(new Rect(Screen.width-235,Screen.height-95,130,55),"HIDE",b))hide=true;}else if(p==P.P){Title("PAUSED");if(GUI.Button(new Rect(Screen.width/2-130,300,260,65),"RESUME",b))Back();if(GUI.Button(new Rect(Screen.width/2-130,390,260,65),"MAIN MENU",b))Menu();}else{Title(end);if(GUI.Button(new Rect(Screen.width/2-130,390,260,65),"MAIN MENU",b))Menu();}}
void Title(string t){GUI.Label(new Rect(0,40,Screen.width,90),t,big());}
GUIStyle big(){return new GUIStyle(s){fontSize=48,alignment=TextAnchor.MiddleCenter};}
void Bar(float x,float y,float v,string n){GUI.DrawTexture(new Rect(x,y,210,15),g);GUI.Label(new Rect(x+220,y-7,120,30),n,s);}
}