using UnityEngine;using System.Collections.Generic;
public class FirstPlayableBatch:MonoBehaviour{
enum M{Menu,Game,Pause,End,Status,Settings}M m;Camera cam;CharacterController cc;GameObject p,e;GUIStyle st,bt,ct;Texture2D gold,dark,red,green;Material wall,wall2,floor,ceil,metal,glow,paper;int f,n;float hp=100,sa=100,sp=100,yaw,pit,msgT,vol=.9f,sens=1,br=.9f,decT;bool key,blue,pow,sw1,sw2,run,use,hide,dec;string msg="",end="";Vector3 et,decP;List<GameObject> objs=new List<GameObject>();List<Light> ls=new List<Light>();string[] notes={"The carpet is wet, but no pipe runs above it.","Three fuses wake the grid. Two switches open maintenance.","Blue opens what yellow cannot.","Lockers only make you quiet.","The black door wants every note."};
[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){if(FindObjectOfType<FirstPlayableBatch>())return;var o=new GameObject("FirstPlayableBatch");DontDestroyOnLoad(o);o.AddComponent<FirstPlayableBatch>();}
void Awake(){foreach(var r in FindObjectsOfType<DesolationRuntime>())r.enabled=false;}
void Start(){Application.targetFrameRate=60;vol=PlayerPrefs.GetFloat("v",.9f);sens=PlayerPrefs.GetFloat("s",1);br=PlayerPrefs.GetFloat("b",.9f);AudioListener.volume=vol;Tex();Style();Mat();World();Menu();}
Texture2D T(Color c){var t=new Texture2D(1,1);t.SetPixel(0,0,c);t.Apply();return t;}
void Tex(){gold=T(new Color(1,.78f,.16f,.95f));dark=T(new Color(0,0,0,.75f));red=T(new Color(.7f,0,0,.75f));green=T(new Color(0,.55f,.1f,.75f));}
void Style(){st=new GUIStyle(GUI.skin.label){fontSize=22,fontStyle=FontStyle.Bold,wordWrap=true};bt=new GUIStyle(GUI.skin.button){fontSize=24,fontStyle=FontStyle.Bold};ct=new GUIStyle(st){alignment=TextAnchor.MiddleCenter,fontSize=30};st.normal.textColor=bt.normal.textColor=ct.normal.textColor=new Color(1,.82f,.3f);}
Material Ma(Color c,string r="",float em=0){var sh=Shader.Find("Universal Render Pipeline/Lit");if(!sh)sh=Shader.Find("Standard");var m=new Material(sh);if(m.HasProperty("_Color"))m.color=c;if(m.HasProperty("_BaseColor"))m.SetColor("_BaseColor",c);var tx=r==""?null:Resources.Load<Texture2D>("Textures/"+r);if(tx){if(m.HasProperty("_MainTex"))m.mainTexture=tx;if(m.HasProperty("_BaseMap"))m.SetTexture("_BaseMap",tx);}if(em>0){m.EnableKeyword("_EMISSION");if(m.HasProperty("_EmissionColor"))m.SetColor("_EmissionColor",c*em);}return m;}
void Mat(){wall=Ma(new Color(.55f,.48f,.18f),"wall_leak_color");wall2=Ma(new Color(.34f,.29f,.11f),"wall_leak_alt_c_color");floor=Ma(new Color(.18f,.12f,.05f),"carpet_fabric_color");ceil=Ma(new Color(.24f,.22f,.16f),"office_ceiling_color");metal=Ma(new Color(.25f,.24f,.22f),"painted_metal_color");glow=Ma(new Color(1,.8f,.22f),"office_ceiling_emission",1);paper=Ma(new Color(.94f,.78f,.38f),"plastic_panel_color");}
GameObject B(string n,Vector3 p,Vector3 s,Material m,bool nc=false){var o=GameObject.CreatePrimitive(PrimitiveType.Cube);o.name=n;o.transform.position=p;o.transform.localScale=s;o.GetComponent<Renderer>().material=m;if(nc)Destroy(o.GetComponent<Collider>());return o;}
void A(string n,Vector3 p,Material m,float z){objs.Add(B(n,p,new Vector3(z,z,z),m));}
void World(){RenderSettings.fog=true;RenderSettings.fogDensity=.035f;RenderSettings.ambientLight=new Color(.22f,.19f,.1f)*br;B("floor",new Vector3(0,-.1f,0),new Vector3(86,.2f,86),floor);B("ceil",new Vector3(0,2.8f,0),new Vector3(86,.1f,86),ceil,true);for(int i=-10;i<=10;i++){B("wall",new Vector3(i*4,1.2f,-42),new Vector3(4,2.5f,.3f),wall);B("wall",new Vector3(i*4,1.2f,42),new Vector3(4,2.5f,.3f),wall);B("wall",new Vector3(-42,1.2f,i*4),new Vector3(.3f,2.5f,4),wall);B("wall",new Vector3(42,1.2f,i*4),new Vector3(.3f,2.5f,4),wall);}for(int x=-6;x<=6;x+=2)for(int z=-6;z<=6;z+=2){if(Mathf.Abs(x)+Mathf.Abs(z)<4)continue;if((x+z)%4==0)B("pillar",new Vector3(x*5,1.2f,z*5),new Vector3(1.1f,2.5f,1.1f),Random.value>.3f?wall:wall2);}for(int i=0;i<24;i++){var l=new GameObject("lamp").AddComponent<Light>();l.transform.position=new Vector3(Random.Range(-35,35),2.45f,Random.Range(-35,35));l.type=LightType.Point;l.range=8;l.intensity=.55f*br;l.color=new Color(1,.8f,.35f);ls.Add(l);B("lampbox",l.transform.position,new Vector3(1.2f,.05f,.4f),glow,true);}A("fuse",new Vector3(-18,.5f,-12),glow,.55f);A("fuse",new Vector3(14,.5f,-18),glow,.55f);A("fuse",new Vector3(-9,.5f,24),glow,.55f);A("key",new Vector3(-28,.5f,6),paper,.45f);A("blue",new Vector3(31,.5f,-22),paper,.45f);A("switchA",new Vector3(2,.8f,22),metal,.6f);A("switchB",new Vector3(18,.8f,12),metal,.6f);A("breaker",new Vector3(26,1,-6),metal,1);A("exit",new Vector3(36,1.2f,32),metal,2);A("truth",new Vector3(-36,1.2f,34),Ma(Color.black),2);A("locker",new Vector3(-20,1,10),metal,1.4f);A("locker",new Vector3(4,1,-26),metal,1.4f);for(int i=0;i<5;i++)A("note",new Vector3(-26+i*13,.7f,-28+(i%2)*48),paper,.5f);p=new GameObject("Player");p.transform.position=new Vector3(-24,1.2f,-24);cc=p.AddComponent<CharacterController>();cc.height=1.75f;cc.radius=.32f;cam=new GameObject("Camera").AddComponent<Camera>();cam.transform.SetParent(p.transform);cam.transform.localPosition=new Vector3(0,1.55f,0);cam.gameObject.AddComponent<AudioListener>();e=GameObject.CreatePrimitive(PrimitiveType.Capsule);e.name="Entity";e.transform.position=et=new Vector3(24,1,22);e.GetComponent<Renderer>().material=Ma(Color.black);Destroy(e.GetComponent<Collider>());}
void Menu(){m=M.Menu;p.SetActive(false);e.SetActive(false);cam.transform.SetParent(null);cam.transform.position=new Vector3(0,1.6f,-9);cam.transform.rotation=Quaternion.Euler(5,0,0);Cursor.lockState=CursorLockMode.None;Cursor.visible=true;}
void Run(){m=M.Game;p.SetActive(true);e.SetActive(true);p.transform.position=new Vector3(-24,1.2f,-24);e.transform.position=new Vector3(24,1,22);f=n=0;key=blue=pow=sw1=sw2=false;hp=sa=sp=100;Cursor.lockState=CursorLockMode.Locked;Cursor.visible=false;Msg("LEVEL 0",3);}
void Save(){PlayerPrefs.SetFloat("x",p.transform.position.x);PlayerPrefs.SetFloat("z",p.transform.position.z);PlayerPrefs.SetInt("f",f);PlayerPrefs.SetInt("n",n);PlayerPrefs.SetInt("k",key?1:0);PlayerPrefs.SetInt("bl",blue?1:0);PlayerPrefs.SetInt("po",pow?1:0);PlayerPrefs.Save();Msg("SAVED",2);}
void Load(){Run();p.transform.position=new Vector3(PlayerPrefs.GetFloat("x",-24),1.2f,PlayerPrefs.GetFloat("z",-24));f=PlayerPrefs.GetInt("f");n=PlayerPrefs.GetInt("n");key=PlayerPrefs.GetInt("k")==1;blue=PlayerPrefs.GetInt("bl")==1;pow=PlayerPrefs.GetInt("po")==1;}
void Update(){if(Input.GetKeyDown(KeyCode.Escape)||Input.GetKeyDown(KeyCode.Backspace))Back();if(m!=M.Game)return;Inp();Move();Near();AI();for(int i=0;i<ls.Count;i++)ls[i].intensity=Mathf.Lerp(.2f,.85f,Mathf.PerlinNoise(i,Time.time*1.7f))*br;if(msgT>0)msgT-=Time.deltaTime;if(hp<=0||sa<=0)End("CONSUMED");run=use=hide=dec=false;}
void Inp(){run=Input.GetKey(KeyCode.LeftShift);use=Input.GetKeyDown(KeyCode.E);hide=Input.GetKey(KeyCode.C)||Input.GetKey(KeyCode.LeftControl);dec=Input.GetKeyDown(KeyCode.Q);}
void Move(){var v=new Vector2(Input.GetAxisRaw("Horizontal"),Input.GetAxisRaw("Vertical"));float s=hide?1.2f:run&&sp>4?4.7f:2.5f;var q=p.transform.right*v.x+p.transform.forward*v.y;q=Vector3.ClampMagnitude(q,1)*s;q.y=-9.8f;cc.Move(q*Time.deltaTime);yaw+=Input.GetAxis("Mouse X")*sens*3;pit=Mathf.Clamp(pit-Input.GetAxis("Mouse Y")*sens*3,-70,70);p.transform.rotation=Quaternion.Euler(0,yaw,0);cam.transform.localRotation=Quaternion.Euler(pit,0,0);sp=Mathf.Clamp(sp+Time.deltaTime*10-(run?Time.deltaTime*28:0),0,100);}
GameObject Closest(){GameObject best=null;float bd=2.8f;foreach(var o in objs){if(!o||!o.activeSelf)continue;float d=Vector3.Distance(p.transform.position,o.transform.position);if(d<bd){bd=d;best=o;}}return best;}
void Near(){var o=Closest();if(o&&o.name=="locker"&&hide){sa=Mathf.Min(100,sa+Time.deltaTime*5);return;}if(dec&&decT<=0){decT=8;decP=p.transform.position+p.transform.forward*5;B("decoy",decP+Vector3.up*.2f,new Vector3(.3f,.3f,.3f),glow,true);Msg("DISTRACTION",2);}if(decT>0)decT-=Time.deltaTime;if(!o||!use)return;string z=o.name;if(z=="fuse"){f++;o.SetActive(false);Msg("FUSE "+f+"/3",2);}else if(z=="key"){key=true;o.SetActive(false);Msg("YELLOW KEY",2);}else if(z=="blue"){blue=true;o.SetActive(false);Msg("BLUE KEY",2);}else if(z=="note"){Msg(notes[Mathf.Clamp(n,0,4)],4);n=Mathf.Min(5,n+1);o.SetActive(false);}else if(z=="switchA"){sw1=true;Msg("SWITCH A",2);}else if(z=="switchB"){sw2=true;Msg("SWITCH B",2);}else if(z=="breaker"){if(f>=3&&sw1&&sw2){pow=true;Save();Msg("POWERED",2);}else Msg("NEEDS FUSES AND SWITCHES",2);}else if(z=="exit"){if(pow)End(sa>55?"ESCAPED":"HOLLOW ESCAPE");else Msg("POWER THE EXIT",2);}else if(z=="truth"){if(pow&&n>=5)End("TRUTH DOOR");else Msg("NEEDS POWER AND NOTES",2);}}
void AI(){bool h=Closest()&&Closest().name=="locker"&&hide;Vector3 ep=e.transform.position,pp=p.transform.position;bool chase=Vector3.Distance(ep,pp)<(h?2:15);if(decT>0)et=decP;else if(chase)et=pp;else if(Vector3.Distance(ep,et)<1.5f)et=new Vector3(Random.Range(-33,33),1,Random.Range(-33,33));Vector3 d=et-ep;d.y=0;if(d.sqrMagnitude>.2f){e.transform.rotation=Quaternion.LookRotation(d.normalized);e.transform.position+=d.normalized*(chase?3.1f:1.4f)*Time.deltaTime;}float dist=Vector3.Distance(e.transform.position,pp);if(dist<2&&!h){hp-=Time.deltaTime*25;sa-=Time.deltaTime*18;}else if(chase&&!h)sa-=Time.deltaTime*4;else sa=Mathf.Min(100,sa+Time.deltaTime*.6f);}
void End(string x){end=x;Save();m=M.End;p.SetActive(false);e.SetActive(false);cam.transform.SetParent(null);cam.transform.position=new Vector3(0,1.6f,-9);cam.transform.rotation=Quaternion.Euler(5,0,0);Cursor.lockState=CursorLockMode.None;Cursor.visible=true;}
void Back(){if(m==M.Game){Save();m=M.Pause;Cursor.lockState=CursorLockMode.None;Cursor.visible=true;}else if(m==M.Pause){m=M.Game;Cursor.lockState=CursorLockMode.Locked;Cursor.visible=false;}else Menu();}
void Msg(string x,float t){msg=x;msgT=t;}
void OnGUI(){GUI.DrawTexture(new Rect(0,0,Screen.width,Screen.height),dark);if(m==M.Menu){Title("DESOLATION: THE BACKROOMS");But(70,220,"PLAY",Run);But(70,310,"LOAD",Load);But(70,400,"SETTINGS",()=>m=M.Settings);But(70,490,"STATUS",()=>m=M.Status);}else if(m==M.Settings){Title("SETTINGS");vol=Sl(230,"VOLUME",vol,0,1);sens=Sl(310,"SENSITIVITY",sens,.35f,2);br=Sl(390,"BRIGHTNESS",br,.35f,1.2f);if(GUI.Button(new Rect(Screen.width/2-100,500,200,55),"SAVE",bt)){PlayerPrefs.SetFloat("v",vol);PlayerPrefs.SetFloat("s",sens);PlayerPrefs.SetFloat("b",br);PlayerPrefs.Save();Prefs();Menu();}}else if(m==M.Status){Title("STATUS");GUI.Label(new Rect(120,230,Screen.width-240,360),"This batch adds Unity use of the uploaded Godot textures, more Level 0 geometry, notes, switches, breaker route, truth door, decoy distraction, hiding pressure, save/load, and a cleaner HUD.\n\nStill needs phone QA, final audio, final icon/screenshots/trailer/privacy text, and more polish.",st);if(GUI.Button(new Rect(Screen.width/2-90,Screen.height-90,180,55),"BACK",bt))Menu();}else if(m==M.Game){GUI.Label(new Rect(25,20,600,35),f<3?"Find fuses "+f+"/3":!key?"Find yellow key":!blue?"Find blue key":!pow?"Power breaker":"Escape",st);Bar(25,60,hp,"HEALTH");Bar(25,86,sa,"SANITY");Bar(25,112,sp,"STAMINA");var o=Closest();if(o)GUI.Label(new Rect(0,Screen.height*.72f,Screen.width,45),o.name.ToUpper()+" [E]",ct);if(msgT>0)GUI.Label(new Rect(0,150,Screen.width,45),msg,ct);if(GUI.Button(new Rect(Screen.width-160,Screen.height-160,130,55),"USE",bt))use=true;if(GUI.RepeatButton(new Rect(Screen.width-310,Screen.height-160,130,55),"SPRINT",bt))run=true;if(GUI.RepeatButton(new Rect(Screen.width-235,Screen.height-95,130,55),"HIDE",bt))hide=true;if(GUI.Button(new Rect(Screen.width-385,Screen.height-95,130,55),"DECOY",bt))dec=true;}else if(m==M.Pause){Title("PAUSED");But(Screen.width/2-130,300,"RESUME",Back);But(Screen.width/2-130,390,"SAVE",Save);But(Screen.width/2-130,480,"MENU",Menu);}else{Title(end);But(Screen.width/2-130,390,"MENU",Menu);}}
float Sl(float y,string l,float v,float a,float b0){GUI.Label(new Rect(140,y,230,35),l,st);return GUI.HorizontalSlider(new Rect(390,y+10,Screen.width-540,30),v,a,b0);}
void Title(string x){GUI.Label(new Rect(0,55,Screen.width,90),x,new GUIStyle(ct){fontSize=46});}
void But(float x,float y,string t,System.Action a){if(GUI.Button(new Rect(x,y,260,65),t,bt))a();}
void Bar(float x,float y,float v,string l){GUI.DrawTexture(new Rect(x,y,220,16),v<30?red:v<60?gold:green);GUI.Label(new Rect(x+230,y-6,120,25),l,small);}
}
