using UnityEngine;using System;using System.Collections.Generic;using System.Reflection;
public sealed class GameplayMobileCompletion:MonoBehaviour{
enum A{Patrol,Investigate,Search,Chase,Attack,GiveUp}FirstPlayableBatch r;Type rt;GameObject p,e;Camera cam;CharacterController cc;A ai;Vector3 target,heard;float t,atk,touch=1,scale=1;int note;bool valve,code,pressure,swc,badge,hidden,slots;GUIStyle gs;Texture2D bg;Dictionary<string,Rect> rc=new Dictionary<string,Rect>();List<GameObject>x=new List<GameObject>();Vector2 ms,ma;int mf=-1;
[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){if(!FindObjectOfType<GameplayMobileCompletion>()){var g=new GameObject("GameplayMobileCompletion");DontDestroyOnLoad(g);g.AddComponent<GameplayMobileCompletion>();}}
void Start(){touch=PlayerPrefs.GetFloat("d_touch",1);scale=PlayerPrefs.GetFloat("d_scale",1);rc["USE"]=LR("USE",.86f,.70f,.11f,.09f);rc["SPRINT"]=LR("SPRINT",.72f,.70f,.12f,.09f);rc["HIDE"]=LR("HIDE",.79f,.82f,.11f,.08f);rc["DECOY"]=LR("DECOY",.64f,.82f,.12f,.08f);rc["BAG"]=LR("BAG",.86f,.08f,.1f,.07f);bg=new Texture2D(1,1);bg.SetPixel(0,0,new Color(0,0,0,.78f));bg.Apply();gs=new GUIStyle(GUI.skin.button){fontSize=21,fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter};gs.normal.textColor=new Color(1,.82f,.3f);}
Rect LR(string k,float a,float b,float c,float d){return new Rect(PlayerPrefs.GetFloat("d_"+k+"x",a),PlayerPrefs.GetFloat("d_"+k+"y",b),c,d);}
void SaveR(){foreach(var k in rc.Keys){PlayerPrefs.SetFloat("d_"+k+"x",rc[k].x);PlayerPrefs.SetFloat("d_"+k+"y",rc[k].y);}PlayerPrefs.SetFloat("d_touch",touch);PlayerPrefs.SetFloat("d_scale",scale);PlayerPrefs.Save();}
bool F(){if(!r){r=FindObjectOfType<FirstPlayableBatch>();if(!r)return false;rt=r.GetType();Extra();}p=G<GameObject>("p");e=G<GameObject>("e");cam=G<Camera>("cam");cc=G<CharacterController>("cc");if(!cc&&p)cc=p.GetComponent<CharacterController>();return p&&e&&cam;}
T G<T>(string n)where T:class{var f=rt.GetField(n,BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public);return f==null?null:f.GetValue(r)as T;}object R(string n){var f=rt.GetField(n,BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public);return f==null?null:f.GetValue(r);}void W(string n,object v){var f=rt.GetField(n,BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public);if(f!=null)f.SetValue(r,v);}bool B(string n){var v=R(n);return v is bool&&(bool)v;}float FL(string n){var v=R(n);return v is float?(float)v:0;}string S(){var v=R("s");return v==null?"":v.ToString();}
void Extra(){if(x.Count>0)return;var m=new Material(Shader.Find("Standard"));m.color=new Color(.25f,.24f,.22f);var y=new Material(Shader.Find("Standard"));y.color=new Color(.95f,.72f,.25f);Add("clueA",new Vector3(-34,.7f,-34),y,.55f);Add("valve",new Vector3(-34,1,18),m,.9f);Add("codepanel",new Vector3(-18,1,30),m,.9f);Add("pressure",new Vector3(8,1,34),m,.9f);Add("switchC",new Vector3(-10,.8f,12),m,.65f);Add("badge",new Vector3(-36,.55f,34),y,.45f);Add("clueB",new Vector3(24,.7f,26),y,.55f);}
void Add(string n,Vector3 p0,Material m,float s){var o=GameObject.CreatePrimitive(PrimitiveType.Cube);o.name=n;o.transform.position=p0;o.transform.localScale=Vector3.one*s;o.GetComponent<Renderer>().material=m;x.Add(o);}
void LateUpdate(){if(!F()||S()!="Game")return;Touch();Move();Puzzle();Brain();Cull();}
void Touch(){for(int i=0;i<Input.touchCount;i++){var q=Input.GetTouch(i);var g=new Vector2(q.position.x,Screen.height-q.position.y);if(Over(g))continue;if(q.position.x<Screen.width*.45f){if(q.phase==TouchPhase.Began&&mf<0){mf=q.fingerId;ms=q.position;}if(q.fingerId==mf){ma=Vector2.ClampMagnitude((q.position-ms)/(120f*scale),1);if(q.phase==TouchPhase.Ended||q.phase==TouchPhase.Canceled)mf=-1;}}else if(q.phase==TouchPhase.Moved){float yaw=FL("yaw")+q.deltaPosition.x*touch*.08f,pit=Mathf.Clamp(FL("pit")-q.deltaPosition.y*touch*.08f,-70,70);W("yaw",yaw);W("pit",pit);p.transform.rotation=Quaternion.Euler(0,yaw,0);cam.transform.localRotation=Quaternion.Euler(pit,0,0);}}}
bool Over(Vector2 q){foreach(var r0 in rc.Values)if(SR(r0).Contains(q))return true;return false;}
void Move(){if(ma.sqrMagnitude<.03f||!cc)return;Vector3 m=p.transform.right*ma.x+p.transform.forward*ma.y;m=Vector3.ClampMagnitude(m,1)*(B("run")?4.5f:2.5f);m.y=-9.8f;cc.Move(m*Time.deltaTime);if(ma.magnitude>.55f)heard=p.transform.position;}
void Puzzle(){GameObject n=null;float d0=2.6f;foreach(var o in x){if(!o||!o.activeSelf)continue;float d=Vector3.Distance(p.transform.position,o.transform.position);if(d<d0){d0=d;n=o;}}if(!n||!B("use"))return;if(n.name=="clueA"){note++;n.SetActive(false);Say("Clue: valve, code 271, pressure, switches A-C-B.");}else if(n.name=="clueB"){note++;n.SetActive(false);Say("Clue: the black badge belongs to the truth door.");}else if(n.name=="valve"){if(!B("bk")){Say("The valve cage needs the blue key.");return;}valve=true;Say("Valve opened.");}else if(n.name=="codepanel"){if(note<1){Say("The code panel needs the clue.");return;}code=true;Say("Code 271 accepted.");}else if(n.name=="pressure"){if(!valve||!code){Say("Pressure needs valve and code panel first.");return;}pressure=true;Say("Pressure stabilized.");}else if(n.name=="switchC"){if(!B("swA")){Say("Start the switch chain with A.");return;}swc=true;Say("Switch C is live. Finish with B.");}else if(n.name=="badge"){if(note<2){Say("The badge has no name yet.");return;}badge=true;n.SetActive(false);Say("Black badge acquired.");}if(!(valve&&code&&pressure&&swc))W("pow",false);PlayerPrefs.SetInt("d_note",note);PlayerPrefs.SetInt("d_v",valve?1:0);PlayerPrefs.SetInt("d_co",code?1:0);PlayerPrefs.SetInt("d_pr",pressure?1:0);PlayerPrefs.SetInt("d_c",swc?1:0);PlayerPrefs.SetInt("d_ba",badge?1:0);PlayerPrefs.Save();}
void Say(string s){W("msg",s);W("msgT",3f);}
bool See(){Vector3 a=e.transform.position+Vector3.up*1.2f,b0=p.transform.position+Vector3.up*1.2f,d=b0-a;if(d.magnitude>18||Vector3.Angle(e.transform.forward,d)>68)return false;RaycastHit h;if(Physics.Raycast(a,d.normalized,out h,d.magnitude-.2f)&&!h.collider.GetComponent<CharacterController>())return false;return true;}
bool Safe(){foreach(var o in GameObject.FindObjectsOfType<GameObject>())if(o.name.Contains("locker")&&Vector3.Distance(o.transform.position,p.transform.position)<2.7f&&B("hide"))return !(Vector3.Distance(e.transform.position,p.transform.position)<4&&See());return false;}
void Brain(){hidden=Safe();bool see=See()&&!hidden,hear=heard!=Vector3.zero&&Vector3.Distance(heard,e.transform.position)<14&&!hidden;if(see){ai=A.Chase;target=p.transform.position;t=7;}else if(hear&&ai!=A.Chase){ai=A.Investigate;target=heard;t=5;heard=Vector3.zero;}if(B("dec")){ai=A.Investigate;target=p.transform.position+p.transform.forward*6;t=5;}if(ai==A.Patrol&&Vector3.Distance(e.transform.position,target)<1.2f)target=new Vector3(UnityEngine.Random.Range(-30,30),1,UnityEngine.Random.Range(-30,30));if(ai==A.Investigate&&Vector3.Distance(e.transform.position,target)<1.3f){ai=A.Search;t=4;}if(ai==A.Search){t-=Time.deltaTime;target=p.transform.position+new Vector3(Mathf.Sin(Time.time*2)*3,0,Mathf.Cos(Time.time*2)*3);if(t<=0){ai=A.GiveUp;t=2;}}if(ai==A.Chase&&(hidden||(!see&&(t-=Time.deltaTime)<=0))){ai=A.Search;t=4;}if(ai==A.GiveUp&&(t-=Time.deltaTime)<=0)ai=A.Patrol;Vector3 d=target-e.transform.position;d.y=0;float sp=ai==A.Chase?3.45f:ai==A.Search?2.15f:1.45f;if(d.sqrMagnitude>.1f){e.transform.rotation=Quaternion.Slerp(e.transform.rotation,Quaternion.LookRotation(d.normalized),Time.deltaTime*5);e.transform.position+=d.normalized*sp*Time.deltaTime;}if(Vector3.Distance(e.transform.position,p.transform.position)<2.1f&&!hidden){ai=A.Attack;atk-=Time.deltaTime;if(atk<=0){atk=1.2f;W("hp",Mathf.Max(0,FL("hp")-14));W("sa",Mathf.Max(0,FL("sa")-10));Say("The entity attacks.");}}}
void Cull(){foreach(var rr in FindObjectsOfType<Renderer>()){if(!rr||rr.transform.IsChildOf(p.transform)||rr.gameObject==e)continue;Vector3 to=rr.bounds.center-cam.transform.position;float d=to.magnitude,dot=Vector3.Dot(cam.transform.forward,to.normalized);bool ground=rr.name.Contains("floor")||rr.name.Contains("ceiling");rr.enabled=d<7||(dot>-.06f&&d<42)||(ground&&dot>.2f&&d<26);}}
Rect SR(Rect n){return new Rect(Screen.width*n.x,Screen.height*n.y,Screen.width*n.width*scale,Screen.height*n.height*scale);}
void OnGUI(){if(!F())return;string st=S();if(st=="Game"){foreach(string k in rc.Keys)if(GUI.Button(SR(rc[k]),k,gs)){if(k=="USE")W("use",true);if(k=="SPRINT")W("run",true);if(k=="HIDE")W("hide",true);if(k=="DECOY")W("dec",true);}GUI.Label(new Rect(25,170,520,30),"AI "+ai.ToString().ToUpper()+"  EXTRA "+(valve&&code&&pressure&&swc?"READY":"PUZZLE ACTIVE"));}if(st=="Menu"){if(GUI.Button(new Rect(Screen.width-260,120,220,55),slots?"CLOSE SLOTS":"SAVE SLOTS",gs))slots=!slots;if(slots)Slots();}if(st=="Settings")Panel();}
void Slots(){GUI.DrawTexture(new Rect(Screen.width-430,190,390,320),bg);for(int i=0;i<3;i++){float y=215+i*88;GUI.Label(new Rect(Screen.width-405,y,230,40),"Slot "+(i+1)+" preview\n"+PlayerPrefs.GetString("d_slot_"+i,"Ready"));if(GUI.Button(new Rect(Screen.width-170,y,100,42),"SAVE",gs)){PlayerPrefs.SetString("d_slot_"+i,"Notes "+note+" Extra "+(valve&&code&&pressure&&swc?"done":"active"));}if(GUI.Button(new Rect(Screen.width-170,y+44,100,36),"LOAD",gs)){note=PlayerPrefs.GetInt("d_note",0);valve=PlayerPrefs.GetInt("d_v",0)==1;code=PlayerPrefs.GetInt("d_co",0)==1;pressure=PlayerPrefs.GetInt("d_pr",0)==1;swc=PlayerPrefs.GetInt("d_c",0)==1;badge=PlayerPrefs.GetInt("d_ba",0)==1;}}}
void Panel(){GUI.DrawTexture(new Rect(65,150,430,500),bg);GUI.Label(new Rect(85,165,380,70),"Mobile controls, accessibility scale, and touch-look tuning");touch=GUI.HorizontalSlider(new Rect(190,245,250,25),touch,.35f,2.5f);scale=GUI.HorizontalSlider(new Rect(190,290,250,25),scale,.8f,1.55f);int row=0;foreach(string k in new[]{"USE","SPRINT","HIDE","DECOY","BAG"}){float y=335+row*48;GUI.Label(new Rect(85,y,80,35),k);if(GUI.Button(new Rect(165,y,45,35),"<",gs))N(k,-.025f,0);if(GUI.Button(new Rect(215,y,45,35),">",gs))N(k,.025f,0);if(GUI.Button(new Rect(265,y,45,35),"^",gs))N(k,0,-.025f);if(GUI.Button(new Rect(315,y,45,35),"v",gs))N(k,0,.025f);row++;}if(GUI.Button(new Rect(130,590,280,45),"SAVE MOBILE LAYOUT",gs))SaveR();}
void N(string k,float x0,float y0){Rect r0=rc[k];r0.x=Mathf.Clamp01(r0.x+x0);r0.y=Mathf.Clamp01(r0.y+y0);rc[k]=r0;}
}