package com.backrooms.levelzero;

import android.app.*;import android.os.*;import android.view.*;import android.graphics.*;import android.content.*;import android.media.*;import java.util.*;

public class MainActivity extends Activity{
 Game g; Sound s;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);g=new Game(this);s=new Sound(g);setContentView(g);}
 public void onResume(){super.onResume();g.run=true;s.start();}
 public void onPause(){g.run=false;s.stop();super.onPause();}
 public void onBackPressed(){g.pause=!g.pause;}
 static class Game extends View{
  Paint p=new Paint(1);Random r=new Random(7);boolean run=true,pause=false,sprint=false,won=false,hunt=false;float x=2.5f,y=2.5f,a=.2f,sen=1,joyx,joyy,jx,jy,mx,my,lx,ld,bob,stam=1,ex=48.5f,ey=48.5f,monx=44.5f,mony=43.5f,noise=0;int W=51,H=51,lp=-1,rp=-1,sp=-1,q=1,found=0;long last=System.nanoTime();boolean[][] open=new boolean[W][H],lite=new boolean[W][H],btn=new boolean[W][H],pit=new boolean[W][H],chair=new boolean[W][H];
  Game(Context c){super(c);setFocusable(true);SharedPreferences s=c.getSharedPreferences("s",0);sen=s.getFloat("sen",1);q=s.getInt("q",1);gen();}
  void gen(){boolean[][] v=new boolean[W][H];Stack<int[]> st=new Stack<>();st.push(new int[]{1,1});v[1][1]=open[1][1]=true;int[][] D={{2,0},{-2,0},{0,2},{0,-2}};while(!st.empty()){int[] c=st.peek();ArrayList<int[]> ds=new ArrayList<>();for(int[] d:D){int nx=c[0]+d[0],ny=c[1]+d[1];if(nx>0&&ny>0&&nx<W-1&&ny<H-1&&!v[nx][ny])ds.add(d);}if(ds.isEmpty())st.pop();else{int[] d=ds.get(r.nextInt(ds.size()));open[c[0]+d[0]/2][c[1]+d[1]/2]=true;open[c[0]+d[0]][c[1]+d[1]]=true;v[c[0]+d[0]][c[1]+d[1]]=true;st.push(new int[]{c[0]+d[0],c[1]+d[1]});}}for(int i=0;i<340;i++){int xx=1+r.nextInt(W-3),yy=1+r.nextInt(H-3),ww=1+r.nextInt(5),hh=1+r.nextInt(4);for(int ox=0;ox<ww&&xx+ox<W-1;ox++)for(int oy=0;oy<hh&&yy+oy<H-1;oy++)open[xx+ox][yy+oy]=true;}for(int i=1;i<W-1;i++)for(int j=1;j<H-1;j++)if(open[i][j]){lite[i][j]=(i*7+j*13)%5==0;pit[i][j]=r.nextFloat()<.012&&dist(i,j,x,y)>12;chair[i][j]=r.nextFloat()<.018&&dist(i,j,x,y)>9;}place(12,12);place(28,30);place(43,42);open[48][48]=open[47][48]=open[48][47]=lite[48][48]=true;}
  void place(int bx,int by){for(int rr=0;rr<9;rr++)for(int i=Math.max(1,bx-rr);i<Math.min(W-1,bx+rr);i++)for(int j=Math.max(1,by-rr);j<Math.min(H-1,by+rr);j++)if(open[i][j]){btn[i][j]=lite[i][j]=true;return;}}
  protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();long n=System.nanoTime();float dt=Math.min(.05f,(n-last)/1e9f);last=n;if(!pause&&!won)step(dt);draw(c,w,h);hud(c,w,h);if(pause)menu(c,w,h);if(won)end(c,w,h);postInvalidateOnAnimation();}
  void step(float dt){a+=ld*.0048f*sen;ld=0;float mv=Math.min(1,Math.abs(mx)+Math.abs(my));if(sprint&&mv>.1&&stam>.04)stam=Math.max(0,stam-dt*.25f);else stam=Math.min(1,stam+dt*.17f);float spd=(sprint&&stam>.04?4.6f:2.45f)*dt,fx=(float)Math.cos(a),fy=(float)Math.sin(a),rx=-fy,ry=fx,dx=(fx*my+rx*mx)*spd,dy=(fy*my+ry*mx)*spd;if(walk(x+dx,y))x+=dx;if(walk(x,y+dy))y+=dy;if(mv>.05)bob+=dt*(sprint?10:6);monster(dt);for(int i=Math.max(1,(int)x-1);i<=Math.min(W-2,(int)x+1);i++)for(int j=Math.max(1,(int)y-1);j<=Math.min(H-2,(int)y+1);j++)if(btn[i][j]&&dist(x,y,i+.5f,j+.5f)<1.35){btn[i][j]=false;found++;noise=1;}if(found>=3&&dist(x,y,ex,ey)<1.2)won=true;}
  void monster(float dt){float d=dist(x,y,monx,mony);noise=Math.max(0,noise-dt*.15f);hunt=d<(sprint?14:8)||noise>.4;float tx=hunt?x:monx+(float)Math.cos(bob*.27),ty=hunt?y:mony+(float)Math.sin(bob*.21),dx=tx-monx,dy=ty-mony,l=(float)Math.hypot(dx,dy);if(l>.05){dx/=l;dy/=l;float s=(hunt?1.9f:.7f)*dt;if(walk(monx+dx*s,mony))monx+=dx*s;if(walk(monx,mony+dy*s))mony+=dy*s;}if(d<1){x=2.5f;y=2.5f;a=.2f;monx=44.5f;mony=43.5f;noise=1;}}
  boolean walk(float xx,float yy){int i=(int)xx,j=(int)yy;return i>0&&j>0&&i<W-1&&j<H-1&&open[i][j]&&!pit[i][j];}
  float dist(float ax,float ay,float bx,float by){return(float)Math.hypot(ax-bx,ay-by);}
  void draw(Canvas c,int w,int h){p.setStyle(Paint.Style.FILL);p.setShader(new LinearGradient(0,0,0,h/2,0xff5a5432,0xffb8a85a,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h/2,p);p.setShader(new LinearGradient(0,h/2,0,h,0xff756739,0xff302818,Shader.TileMode.CLAMP));c.drawRect(0,h/2,w,h,p);p.setShader(null);int cols=q==0?140:q==1?220:300;float[] z=new float[cols];for(int i=0;i<cols;i++){float ra=a-.6f+1.2f*i/cols;Ray ray=cast(ra);float d=Math.max(.08f,ray.d*(float)Math.cos(ra-a));z[i]=d;int sh=(int)(h/(d*.72f)),top=h/2-sh/2+(int)(Math.sin(bob)*8),bot=h/2+sh/2;float fog=Math.min(1,d/(q==0?13:22));int rr=lerp(ray.side?158:186,72,fog),gg=lerp(ray.side?148:170,68,fog),bb=lerp(ray.side?70:86,42,fog);if(ray.light){rr+=20;gg+=18;}p.setColor(Color.rgb(cl(rr),cl(gg),cl(bb)));float sx=i*w/(float)cols,sw=w/(float)cols+1;c.drawRect(sx,top,sx+sw,bot,p);if(q>0&&d<16&&((int)(ray.hx*5+ray.hy*9))%10==0){p.setColor(0x22332f18);c.drawRect(sx,top,sx+sw,bot,p);}if(ray.light&&d<11){p.setColor(0x88fff2a0);c.drawRect(sx,top-8,sx+sw,top+4,p);}}ArrayList<Spr> ss=sprites();Collections.sort(ss,(u,v)->Float.compare(v.d,u.d));for(Spr s:ss)spr(c,w,h,cols,z,s);hands(c,w,h);post(c,w,h);}
  Ray cast(float ra){float dx=(float)Math.cos(ra),dy=(float)Math.sin(ra);Ray o=new Ray();for(float t=.04f;t<40;t+=.04f){float hx=x+dx*t,hy=y+dy*t;int i=(int)hx,j=(int)hy;if(i<0||j<0||i>=W||j>=H||!open[i][j]){o.d=t;o.hx=hx;o.hy=hy;o.side=Math.abs(hx-i-.5f)>Math.abs(hy-j-.5f);o.light=((Math.max(0,Math.min(W-1,i))+Math.max(0,Math.min(H-1,j)))%5)==0;return o;}}o.d=40;return o;}
  ArrayList<Spr> sprites(){ArrayList<Spr>s=new ArrayList<>();for(int i=1;i<W-1;i++)for(int j=1;j<H-1;j++)if(open[i][j]){float d=dist(x,y,i+.5f,j+.5f);if(d<22&&d>.5){if(btn[i][j])s.add(new Spr(i+.5f,j+.5f,0,d));if(chair[i][j])s.add(new Spr(i+.5f,j+.5f,1,d));if(pit[i][j])s.add(new Spr(i+.5f,j+.5f,2,d));}}s.add(new Spr(monx,mony,3,dist(x,y,monx,mony)));s.add(new Spr(ex,ey,4,dist(x,y,ex,ey)));return s;}
  void spr(Canvas c,int w,int h,int cols,float[]z,Spr s){float dx=s.x-x,dy=s.y-y,d=(float)Math.hypot(dx,dy),rel=norm((float)Math.atan2(dy,dx)-a);if(Math.abs(rel)>.72f||d<.25)return;int sx=(int)((rel/1.2f+.5f)*w),col=Math.max(0,Math.min(cols-1,(int)(sx/(float)w*cols)));if(d>z[col]+.4)return;int size=(int)(h/(d*.85f)),cy=h/2+size/6+(int)(Math.sin(bob)*8);if(s.t==0){p.setColor(0xddff251a);c.drawCircle(sx,cy,size*.13f,p);p.setColor(0x77ffe68a);c.drawCircle(sx,cy,size*.25f,p);}else if(s.t==1){p.setColor(0xffdad4b8);c.drawRect(sx-size*.18f,cy-size*.25f,sx+size*.18f,cy+size*.1f,p);p.setStrokeWidth(Math.max(2,size*.035f));c.drawLine(sx-size*.13f,cy+size*.1f,sx-size*.23f,cy+size*.42f,p);c.drawLine(sx+size*.13f,cy+size*.1f,sx+size*.23f,cy+size*.42f,p);}else if(s.t==2){p.setColor(0xff141008);c.drawOval(new RectF(sx-size*.5f,cy+size*.2f,sx+size*.5f,cy+size*.55f),p);}else if(s.t==4){p.setColor(found>=3?0xff7a351d:0xff231511);c.drawRect(sx-size*.22f,cy-size*.55f,sx+size*.22f,cy+size*.36f,p);p.setColor(found>=3?0xffffe08a:0xff473127);c.drawCircle(sx+size*.12f,cy-size*.05f,Math.max(3,size*.035f),p);}else{p.setColor(Color.argb(cl((int)(245-d*5)),5,4,3));c.drawOval(new RectF(sx-size*.16f,cy-size*.6f,sx+size*.16f,cy+size*.35f),p);c.drawCircle(sx,cy-size*.73f,size*.18f,p);p.setStrokeWidth(Math.max(3,size*.045f));p.setStrokeCap(Paint.Cap.ROUND);c.drawLine(sx-size*.1f,cy-size*.25f,sx-size*.42f,cy+size*.22f,p);c.drawLine(sx+size*.1f,cy-size*.25f,sx+size*.42f,cy+size*.22f,p);c.drawLine(sx-size*.05f,cy+size*.25f,sx-size*.24f,cy+size*.72f,p);c.drawLine(sx+size*.05f,cy+size*.25f,sx+size*.24f,cy+size*.72f,p);p.setColor(0xccffe875);c.drawCircle(sx-size*.06f,cy-size*.75f,Math.max(2,size*.025f),p);c.drawCircle(sx+size*.06f,cy-size*.75f,Math.max(2,size*.025f),p);}}
  void hands(Canvas c,int w,int h){p.setStyle(Paint.Style.FILL);p.setColor(0xffd6c64e);Path L=new Path();L.moveTo(w*.30f,h);L.cubicTo(w*.33f,h*.80f,w*.43f,h*.78f,w*.46f,h);L.close();c.drawPath(L,p);Path R=new Path();R.moveTo(w*.70f,h);R.cubicTo(w*.67f,h*.80f,w*.57f,h*.78f,w*.54f,h);R.close();c.drawPath(R,p);p.setColor(0xff16120d);c.drawOval(new RectF(w*.42f,h*.88f,w*.49f,h*1.03f),p);c.drawOval(new RectF(w*.51f,h*.88f,w*.58f,h*1.03f),p);}
  void post(Canvas c,int w,int h){if(q>0){p.setColor(hunt?0x223a0000:0x11000000);for(int i=0;i<70;i++){float gx=r.nextFloat()*w,gy=r.nextFloat()*h;c.drawRect(gx,gy,gx+2,gy+1,p);}}p.setShader(new RadialGradient(w/2f,h/2f,Math.max(w,h)*.78f,0x00000000,hunt?0xcc000000:0x99000000,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);}
  void hud(Canvas c,int w,int h){p.setTextAlign(Paint.Align.LEFT);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(h*.04f);p.setColor(0xffffe88a);String o=won?"Escaped Level 0":found>=3?"Objective: reach the strange exit door":"Objective: activate red buttons "+found+"/3";c.drawText(o,w*.035f,h*.08f,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(h*.028f);p.setColor(hunt?0xffff9999:0xccffe88a);c.drawText(hunt?"Something heard you.":"Level 0 / The Lobby",w*.035f,h*.125f,p);controls(c,w,h);p.setColor(0x553d321d);c.drawRoundRect(new RectF(w*.035f,h*.91f,w*.31f,h*.93f),8,8,p);p.setColor(stam>.25?0xccffe477:0xccff805c);c.drawRoundRect(new RectF(w*.035f,h*.91f,w*(.035f+.275f*stam),h*.93f),8,8,p);}
  void controls(Canvas c,int w,int h){if(joyx==0){joyx=w*.15f;joyy=h*.75f;jx=joyx;jy=joyy;}p.setColor(0x30fff0a0);c.drawCircle(joyx,joyy,h*.13f,p);p.setColor(0x70fff0a0);c.drawCircle(jx,jy,h*.052f,p);RectF sr=sprintR(w,h);p.setColor(sprint?0x88ffe477:0x44ffe477);c.drawOval(sr,p);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(h*.028f);p.setColor(0xddfff0a0);c.drawText("SPRINT",sr.centerX(),sr.centerY()+h*.01f,p);RectF pr=pauseR(w,h);p.setColor(0x55fff0a0);c.drawRoundRect(pr,8,8,p);p.setTextSize(h*.052f);c.drawText("Ⅱ",pr.centerX(),pr.centerY()+h*.018f,p);p.setTextAlign(Paint.Align.LEFT);}
  void menu(Canvas c,int w,int h){p.setColor(0xd9000000);c.drawRect(0,0,w,h,p);p.setColor(0xee2b281a);c.drawRoundRect(new RectF(w*.26f,h*.16f,w*.74f,h*.84f),18,18,p);p.setTextAlign(Paint.Align.CENTER);p.setColor(0xffffe28a);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(h*.06f);c.drawText("PAUSED",w/2,h*.28f,p);button(c,w*.34f,h*.36f,w*.66f,h*.45f,"Sensitivity "+String.format(Locale.US,"%.1f",sen));button(c,w*.34f,h*.48f,w*.66f,h*.57f,"Graphics: "+(q==0?"Low":q==1?"Medium":"High"));button(c,w*.34f,h*.60f,w*.66f,h*.69f,"Resume");button(c,w*.34f,h*.72f,w*.66f,h*.81f,"Exit Game");p.setTextAlign(Paint.Align.LEFT);}
  void button(Canvas c,float l,float t,float r,float b,String s){RectF rr=new RectF(l,t,r,b);p.setColor(0x66f1dc82);c.drawRoundRect(rr,12,12,p);p.setColor(0xffffe28a);p.setTextSize(getHeight()*.032f);c.drawText(s,rr.centerX(),rr.centerY()+getHeight()*.012f,p);}
  void end(Canvas c,int w,int h){p.setColor(0xe0000000);c.drawRect(0,0,w,h,p);p.setColor(0xffffe28a);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(h*.06f);c.drawText("YOU FOUND THE DOOR",w/2,h*.48f,p);p.setTextSize(h*.034f);c.drawText("Level 0 fades behind you.",w/2,h*.55f,p);p.setTextAlign(Paint.Align.LEFT);}
  public boolean onTouchEvent(MotionEvent e){int ac=e.getActionMasked(),idx=e.getActionIndex(),w=getWidth(),h=getHeight();if(pause&&(ac==0||ac==5)){tap(e.getX(idx),e.getY(idx),w,h);return true;}if(ac==0||ac==5){float X=e.getX(idx),Y=e.getY(idx);int id=e.getPointerId(idx);if(pauseR(w,h).contains(X,Y)){pause=true;return true;}if(sprintR(w,h).contains(X,Y)){sp=id;sprint=true;return true;}if(X<w*.45f&&lp<0){lp=id;joyx=jx=X;joyy=jy=Y;}else if(rp<0)rp=id;}else if(ac==2){for(int i=0;i<e.getPointerCount();i++){int id=e.getPointerId(i);float X=e.getX(i),Y=e.getY(i);if(id==lp){float rad=h*.13f,dx=X-joyx,dy=Y-joyy,l=(float)Math.hypot(dx,dy);if(l>rad){dx*=rad/l;dy*=rad/l;}jx=joyx+dx;jy=joyy+dy;mx=dx/rad;my=-dy/rad;}else if(id==rp&&e.getHistorySize()>0)ld+=X-e.getHistoricalX(i,e.getHistorySize()-1);}}else if(ac==1||ac==6||ac==3){int id=e.getPointerId(idx);if(id==lp){lp=-1;mx=my=0;jx=joyx;jy=joyy;}if(id==rp)rp=-1;if(id==sp){sp=-1;sprint=false;}}return true;}
  void tap(float X,float Y,int w,int h){if(Y>h*.36f&&Y<h*.45f){sen+=.1f;if(sen>2.4f)sen=.5f;save();}else if(Y>h*.48f&&Y<h*.57f){q=(q+1)%3;save();}else if(Y>h*.60f&&Y<h*.69f)pause=false;else if(Y>h*.72f&&Y<h*.81f)((Activity)getContext()).finish();}
  void save(){getContext().getSharedPreferences("s",0).edit().putFloat("sen",sen).putInt("q",q).apply();}
  RectF sprintR(int w,int h){float rr=h*.09f;return new RectF(w-rr*2.6f,h-rr*2.35f,w-rr*.55f,h-rr*.3f);}RectF pauseR(int w,int h){float s=h*.095f;return new RectF(w-s*1.35f,h*.045f,w-s*.35f,h*.045f+s);}int lerp(int A,int B,float t){return(int)(A*(1-t)+B*t);}int cl(int v){return Math.max(0,Math.min(255,v));}float norm(float v){while(v<-Math.PI)v+=Math.PI*2;while(v>Math.PI)v-=Math.PI*2;return v;}static class Ray{float d,hx,hy;boolean side,light;}static class Spr{float x,y,d;int t;Spr(float X,float Y,int T,float D){x=X;y=Y;t=T;d=D;}}
 }
 static class Sound{Thread t;boolean run;Game g;Sound(Game gg){g=gg;}void start(){if(run)return;run=true;t=new Thread(()->{int sr=44100,bs=2048;AudioTrack at=new AudioTrack.Builder().setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_GAME).build()).setAudioFormat(new AudioFormat.Builder().setSampleRate(sr).setChannelMask(AudioFormat.CHANNEL_OUT_STEREO).setEncoding(AudioFormat.ENCODING_PCM_16BIT).build()).setBufferSizeInBytes(bs*4).setTransferMode(AudioTrack.MODE_STREAM).build();short[] o=new short[bs*2];double z=0,fp=0,th=0,nx=3;Random r=new Random();at.play();while(run){for(int i=0;i<bs;i++){z+=1.0/sr;double n=r.nextDouble()*2-1;if(z>nx){th=1;nx=z+4+r.nextDouble()*8;}th*=.9995;double m=Math.min(1,Math.abs(g.mx)+Math.abs(g.my));fp=(fp+m*(g.sprint?.018:.011))%1;double foot=fp<.06?m*.12*Math.sin(z*430):0,hum=.05*Math.sin(z*377)+.025*Math.sin(z*754),buzz=.012*n,mon=g.hunt?(.065*Math.sin(z*42)+.02*n):0,s=hum+buzz+th*.16*Math.sin(z*95)+foot+mon;short v=(short)(Math.max(-1,Math.min(1,s))*32767);o[i*2]=v;o[i*2+1]=(short)(v*.94);}at.write(o,0,o.length,AudioTrack.WRITE_BLOCKING);}at.stop();at.release();});t.start();}void stop(){run=false;}}
}
