package com.backrooms.levelzero;

import android.app.*;import android.os.*;import android.view.*;import android.graphics.*;import android.content.*;import android.media.*;import java.util.*;

public class MainActivity extends Activity{
 Game v; Audio a;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);v=new Game(this);a=new Audio(v);setContentView(v);}
 public void onResume(){super.onResume();v.run=true;if(a!=null)a.start();}
 public void onPause(){v.run=false;if(a!=null)a.stop();super.onPause();}
 public void onBackPressed(){v.pause=!v.pause;}
 static class Game extends View{
  Paint p=new Paint(1);Random r=new Random(9);boolean run=true,pause=false,sprint=false,found=false;float x=2.5f,y=2.5f,ang=.2f,sen=1,joyx,joyy,jx,jy,mx,my,lookx,looky,bob;int lp=-1,rp=-1,sp=-1,quality=1;long last=System.nanoTime();int W=39,H=39;boolean[][] open=new boolean[W][H];String qual(){return quality==0?"Low":quality==1?"Medium":"High";}
  Game(Context c){super(c);setFocusable(true);gen();SharedPreferences s=c.getSharedPreferences("s",0);sen=s.getFloat("sen",1);quality=s.getInt("q",1);}
  void gen(){boolean[][] vis=new boolean[W][H];Stack<int[]> st=new Stack<>();st.push(new int[]{1,1});vis[1][1]=true;while(!st.empty()){int[] c=st.peek();ArrayList<int[]> ds=new ArrayList<>();int[][] D={{2,0},{-2,0},{0,2},{0,-2}};for(int[]d:D){int nx=c[0]+d[0],ny=c[1]+d[1];if(nx>0&&ny>0&&nx<W-1&&ny<H-1&&!vis[nx][ny])ds.add(d);}if(ds.isEmpty()){st.pop();continue;}int[]d=ds.get(r.nextInt(ds.size()));open[c[0]+d[0]/2][c[1]+d[1]/2]=true;open[c[0]+d[0]][c[1]+d[1]]=true;vis[c[0]+d[0]][c[1]+d[1]]=true;st.push(new int[]{c[0]+d[0],c[1]+d[1]});}for(int i=0;i<260;i++){int xx=1+r.nextInt(W-2),yy=1+r.nextInt(H-2);open[xx][yy]=true;}open[1][1]=true;}
  protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();long n=System.nanoTime();float dt=Math.min(.05f,(n-last)/1e9f);last=n;if(!pause)step(dt);draw3d(c,w,h);hud(c,w,h);postInvalidateOnAnimation();}
  void step(float dt){ang+=lookx*.004f*sen;lookx=looky=0;float spd=(sprint?4.2f:2.4f)*dt;float fx=(float)Math.cos(ang),fy=(float)Math.sin(ang),rx=-fy,ry=fx;float dx=(fx*my+rx*mx)*spd,dy=(fy*my+ry*mx)*spd;if(walk(x+dx,y))x+=dx;if(walk(x,y+dy))y+=dy;if(Math.abs(mx)+Math.abs(my)>.05)bob+=dt*(sprint?9:6);found=(x>W-5&&y>H-5);}
  boolean walk(float a,float b){int ix=(int)a,iy=(int)b;if(ix<1||iy<1||ix>=W-1||iy>=H-1)return false;return open[ix][iy];}
  void draw3d(Canvas c,int w,int h){p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(34,32,21));c.drawRect(0,0,w,h,p);LinearGradient ceil=new LinearGradient(0,0,0,h/2,0xff6f693f,0xffb6aa5e,Shader.TileMode.CLAMP);p.setShader(ceil);c.drawRect(0,0,w,h/2,p);LinearGradient fl=new LinearGradient(0,h/2,0,h,0xff6d6234,0xff3d321d,Shader.TileMode.CLAMP);p.setShader(fl);c.drawRect(0,h/2,w,h,p);p.setShader(null);int cols=quality==0?120:quality==1?180:240;for(int i=0;i<cols;i++){float ra=ang-0.62f+1.24f*i/cols;Ray ray=cast(ra);float dist=ray.d*(float)Math.cos(ra-ang);int sh=(int)(h/(dist*.7f));int top=h/2-sh/2+(int)(Math.sin(bob)*8),bot=h/2+sh/2;float fog=Math.min(1,dist/(quality==0?16:24));int yy=(int)(185*(1-fog)+92*fog),gg=(int)(170*(1-fog)+82*fog),bb=(int)(82*(1-fog)+45*fog);if(ray.side) {yy-=16;gg-=13;}p.setColor(Color.rgb(Math.max(0,yy),Math.max(0,gg),Math.max(0,bb)));float sx=i*w/(float)cols,sw=w/(float)cols+1;c.drawRect(sx,top,sx+sw,bot,p);if(((int)(ray.hitx*3+ray.hity*5))%9==0){p.setColor(0x22404020);c.drawRect(sx,top,sx+sw,bot,p);}if(ray.light&&dist<12){p.setColor(0x88fff0a0);c.drawRect(sx,top-8,sx+sw,top+6,p);}}for(int i=0;i<7;i++){float lx=w*(i+.5f)/7;RadialGradient g=new RadialGradient(lx,h*.17f,w*.13f,0x88fff5b0,0x00fff5b0,Shader.TileMode.CLAMP);p.setShader(g);c.drawCircle(lx,h*.17f,w*.13f,p);}p.setShader(null);p.setColor(0x11000000);for(int i=0;i<80&&quality>0;i++){float gx=r.nextFloat()*w,gy=r.nextFloat()*h;c.drawRect(gx,gy,gx+2,gy+1,p);}RadialGradient v=new RadialGradient(w/2,h/2,Math.max(w,h)*.75f,0x00000000,0xaa000000,Shader.TileMode.CLAMP);p.setShader(v);c.drawRect(0,0,w,h,p);p.setShader(null);}
  Ray cast(float a){float dx=(float)Math.cos(a),dy=(float)Math.sin(a),d=.05f;Ray out=new Ray();for(float t=.05f;t<40;t+=d){float xx=x+dx*t,yy=y+dy*t;int ix=(int)xx,iy=(int)yy;if(ix<0||iy<0||ix>=W||iy>=H||!open[ix][iy]){out.d=t;out.hitx=xx;out.hity=yy;out.side=Math.abs(xx-ix-.5f)>Math.abs(yy-iy-.5f);out.light=((ix+iy)%5==0);return out;}}out.d=40;return out;}
  void hud(Canvas c,int w,int h){p.setShader(null);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(h*.045f);p.setColor(0xddf5e69d);c.drawText(found?"Objective: You found the strange exit door.":"Objective: Find the strange exit door",w*.035f,h*.085f,p);p.setTextSize(h*.03f);p.setTypeface(Typeface.DEFAULT);c.drawText("Level 0 / The Lobby",w*.035f,h*.13f,p);if(joyx==0){joyx=w*.15f;joyy=h*.75f;jx=joyx;jy=joyy;}p.setStyle(Paint.Style.FILL);p.setColor(0x33fff0a0);c.drawCircle(joyx,joyy,h*.13f,p);p.setColor(0x66fff0a0);c.drawCircle(jx,jy,h*.055f,p);RectF s=sprint(w,h);p.setColor(sprint?0x88fff0a0:0x44fff0a0);c.drawOval(s,p);p.setColor(0xddfff0a0);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(h*.03f);c.drawText("SPRINT",s.centerX(),s.centerY()+h*.011f,p);RectF pa=pauseR(w,h);p.setColor(0x55fff0a0);c.drawRoundRect(pa,8,8,p);p.setColor(0xddfff0a0);p.setTextSize(h*.055f);c.drawText("Ⅱ",pa.centerX(),pa.centerY()+h*.02f,p);if(pause)menu(c,w,h);p.setTextAlign(Paint.Align.LEFT);}
  void menu(Canvas c,int w,int h){p.setColor(0xd9000000);c.drawRect(0,0,w,h,p);float L=w*.28f,T=h*.18f,R=w*.72f,B=h*.82f;p.setColor(0xee2b281a);c.drawRoundRect(new RectF(L,T,R,B),18,18,p);p.setTextAlign(Paint.Align.CENTER);p.setColor(0xfff1dc82);p.setTextSize(h*.065f);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("PAUSED",w/2,T+h*.11f,p);button(c,w*.36f,T+h*.22f,w*.64f,T+h*.31f,"Sensitivity "+String.format(Locale.US,"%.1f",sen));button(c,w*.36f,T+h*.35f,w*.64f,T+h*.44f,"Graphics: "+qual());button(c,w*.36f,T+h*.49f,w*.64f,T+h*.58f,"Resume");button(c,w*.36f,T+h*.61f,w*.64f,T+h*.70f,"Exit Game");}
  void button(Canvas c,float l,float t,float r,float b,String s){p.setColor(0x55f1dc82);RectF q=new RectF(l,t,r,b);c.drawRoundRect(q,12,12,p);p.setColor(0xfff1dc82);p.setTextSize(getHeight()*.034f);c.drawText(s,q.centerX(),q.centerY()+getHeight()*.012f,p);}
  public boolean onTouchEvent(MotionEvent e){int a=e.getActionMasked(),idx=e.getActionIndex(),w=getWidth(),h=getHeight();if(pause&&(a==0||a==5)){tap(e.getX(idx),e.getY(idx),w,h);return true;}if(a==0||a==5){float X=e.getX(idx),Y=e.getY(idx);int id=e.getPointerId(idx);if(pauseR(w,h).contains(X,Y)){pause=true;return true;}if(sprint(w,h).contains(X,Y)){sp=id;sprint=true;return true;}if(X<w*.45f&&lp<0){lp=id;joyx=jx=X;joyy=jy=Y;}else if(rp<0){rp=id;lookx=X;looky=Y;}}else if(a==2){for(int i=0;i<e.getPointerCount();i++){int id=e.getPointerId(i);float X=e.getX(i),Y=e.getY(i);if(id==lp){float dx=X-joyx,dy=Y-joyy,rad=h*.13f,l=(float)Math.hypot(dx,dy);if(l>rad){dx*=rad/l;dy*=rad/l;}jx=joyx+dx;jy=joyy+dy;mx=dx/rad;my=-dy/rad;}else if(id==rp){float nx=X;lookx=nx-lookx;looky=Y;}}}else if(a==1||a==6||a==3){int id=e.getPointerId(idx);if(id==lp){lp=-1;mx=my=0;jx=joyx;jy=joyy;}if(id==rp)rp=-1;if(id==sp){sp=-1;sprint=false;}}return true;}
  void tap(float X,float Y,int w,int h){float T=h*.18f;if(Y>T+h*.22f&&Y<T+h*.31f){sen=sen>=2.4f?.5f:sen+.1f;save();}else if(Y>T+h*.35f&&Y<T+h*.44f){quality=(quality+1)%3;save();}else if(Y>T+h*.49f&&Y<T+h*.58f)pause=false;else if(Y>T+h*.61f&&Y<T+h*.70f)((Activity)getContext()).finish();}
  void save(){getContext().getSharedPreferences("s",0).edit().putFloat("sen",sen).putInt("q",quality).apply();}
  RectF sprint(int w,int h){float r=h*.09f;return new RectF(w-r*2.6f,h-r*2.3f,w-r*.55f,h-r*.3f);}RectF pauseR(int w,int h){float s=h*.095f;return new RectF(w-s*1.35f,h*.045f,w-s*.35f,h*.045f+s);}static class Ray{float d,hitx,hity;boolean side,light;}
 }
 static class Audio{Thread t;boolean run;Game g;Audio(Game g){this.g=g;}void start(){if(run)return;run=true;t=new Thread(()->{int sr=44100,bs=2048;AudioTrack at=new AudioTrack.Builder().setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_GAME).build()).setAudioFormat(new AudioFormat.Builder().setSampleRate(sr).setChannelMask(AudioFormat.CHANNEL_OUT_STEREO).setEncoding(AudioFormat.ENCODING_PCM_16BIT).build()).setBufferSizeInBytes(bs*4).setTransferMode(AudioTrack.MODE_STREAM).build();short[] o=new short[bs*2];double z=0,step=0,th=0,next=3;Random r=new Random();at.play();while(run){for(int i=0;i<bs;i++){z+=1.0/sr;double n=r.nextDouble()*2-1;if(z>next){th=1;next=z+4+r.nextDouble()*8;}th*=.9997;double m=Math.min(1,Math.abs(g.mx)+Math.abs(g.my));step=(step+m*.012)%1;double foot=step<.08?m*.12*Math.sin(z*430):0;double s=.05*Math.sin(z*377)+.025*Math.sin(z*754)+.012*n+th*.18*Math.sin(z*180)+foot;short v=(short)(Math.max(-1,Math.min(1,s))*32767);o[i*2]=v;o[i*2+1]=(short)(v*.94);}at.write(o,0,o.length,AudioTrack.WRITE_BLOCKING);}at.release();});t.start();}void stop(){run=false;}}
}